### ISSUE TITLE
Missing Title?

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#100]
![image](https://github.com/akeeba/panopticon/assets/1296369/257b4994-bd4b-4f5b-8cdb-0066a3069605)

Not sure if there is supposed to be a title here or not. If there is not then the empty h2 needs to be removed

![image](https://github.com/akeeba/panopticon/assets/1296369/b293002e-3cb9-4aa2-bd18-bac4656fa3e7)

**Comment by brianteeman** [comment]
actualy I am finding this on more and more pages

**Comment by nikosdion** [comment]
Check the template’s index.php file. I believe this is where an if block is needed. I’m not at home now, I can’t check myself. If you find and do a PR I can merge it.

**Comment by brianteeman** [comment]
Not at home either :)
