### ISSUE TITLE
$type = "text/javascript"

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#102]
Upstream AWF

>  Authors are encouraged to omit the attribute if the script refers to JavaScript code rather than specify a MIME type.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by nikosdion** [comment]
I’ve seen stupid hosts which deliver .JS files with the MIME type text/plain. Overriding it makes sense in this case.

**Comment by brianteeman** [comment]
Your choice but all testing software will flag this

**Comment by nikosdion** [comment]
If any testing software treats a mere weak suggestion (“are encouraged” != “MUST”) as an error, I'd posit that said testing software is broken and in disconnect with the reality of commercial hosting.

If the HTML standard is updated to _disallow_ the `type` attribute to contain any JavaScript MIME type on pain of the script not executing then, yes, it is a problem to be addressed.

Until then, I prefer writing my software for _humans_, not automated tools.
