### ISSUE TITLE
vh-100

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#107]
`<div class="vh-100"></div>`

Not sure what the intention was for adding this line at the end of these files but it doesnt seem to be correct

> ViewTemplates\Selfupdate\default_noupdate.blade.php
> ViewTemplates\Users\form.blade.php

**Comment by nikosdion** [comment]
It is intentional. Otherwise the footer ended up midway through the window height even on a 14” laptop. I want it stuck to the bottom of the window. 

This is the only page I had to do that, the others are naturally long enough. That’s why it looks confusing to you.

**Comment by brianteeman** [comment]
So I should flag up the other pages where the footer is not at the bottom

**Comment by nikosdion** [comment]
Yup
