### ISSUE TITLE
Allow extensions list to be filtered by update status (has update, no updates) and update method (manual, automatic)

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#108]
![image](https://github.com/akeeba/panopticon/assets/1296369/6098b269-c804-4c9b-8bfa-b1b93eca7f21)

On this site as you can imagine its pretty hard to find the extension that needs to be updated. It would be great if there was a filter that will show "Extensions with Update available"

**Comment by nikosdion** [comment]
Heh. This has nothing on my dev site ;)

Joking aside, this is something I already had in mind to  implement in a future version. Right now I want to make sure things work smoothly before making them more usable (avoiding the “lipstick on a pig” issue). 

Also, for now, I want people to mostly use Panopticon to auto-install updates. This is the hard stuff I need to make sure is working right.
