### ISSUE TITLE
Feature Request - Extension Update Status

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#109]
If I change the default for an extension as below

![image](https://github.com/akeeba/panopticon/assets/1296369/c18b1f7d-0bfd-4241-a5a8-eb756113ac90)

Then it would be great if there was an indicator fr the selected update preference

![image](https://github.com/akeeba/panopticon/assets/1296369/aec1fe81-d82e-429e-9148-5da73502d5ad)

Or maybe another filter option - to filter all the extensions on the list to show their update preference

**Comment by nikosdion** [comment]
It should already display a magic wand icon to indicate auto-updates. I will check when I’m back in front of a real computer.

**Comment by brianteeman** [comment]
It does but when you have 1 magic wand on 100 extensions it's hard to find

**Comment by nikosdion** [comment]
As I said, this is already planned, see https://github.com/akeeba/panopticon/issues/108
