### ISSUE TITLE
Update Preferences

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#113]
I may not have considered this properly but here goes anyway

As I read it there are 4 options

Release | do nothing | patch only | minor only | everything
--|--|--|--|--
1.0.1 | |YES| | YES
1.1.0|| |YES | YES
2.0.0| | ||YES

So unless I misunderstand (probably do) I can not set an extension to be updated **only for major** or **everything but major**

**Comment by nikosdion** [comment]
Do nothing: DO NOT upgrade to new patch, minor, and major versions. Turns off automatic updates. Default setting as it will not break anything on any site  (obviously).

Patch: upgrade to new patch e.g. 1.0.0 to 1.0.1. DO NOT upgrade to new minor (e.g. 1.1.0), and major (e.g. 2.0.0). Most conservative setting, what you need for extensions which absolutely do not follow semantic versioning, or if your template overrides are so extensive they require a manual review on every single minor release.

Minor: Upgrade to new patch (e.g. 1.0.0 to 1.0.1), and minor (e.g. 1.0.0 to 1.1.0). DO NOT upgrade to new major (e.g. 2.0.0). What you need for most extensions which follow semantic versioning.

Major: Upgrade to new patch (e.g. 1.0.0 to 1.0.1), new minor (e.g. 1.0.0 to 1.1.0), and new major (e.g. 1.0.0 to 1.2.0). Only for extensions which never, _ever_ break your site upon upgrade (e.g. Akeeba Backup, and Admin Tools, most Regular Labs extensions, etc).

There is no point having an option to only update if there is a new major release. If you can trust the new major won't break things then  you can trust that neither minor nor patch releases will break anything anything either. Therefore, you can select major.

Upgrading to everything but major means that you only want to upgrade to patch, and minor releases. In this case you select minor.

**Comment by brianteeman** [comment]
ah - they are inclusive of the level below and not exclusive to the named level
