### ISSUE TITLE
Colorise update methods for core Joomla and extensions

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#117]
So it's easier to figure out what's set to what

**Comment by nikosdion** [comment]
Unfortunately, Bootstrap does not provide a method to do that. We'd need to write custom JavaScript, but it runs into performance issues since we have so many selects.

**Comment by brianteeman** [comment]
Not a bootstrap specific problem. its simply not possible without js - dam annoying though

**Comment by brianteeman** [comment]
You can get very very close using the has selector

https://codepen.io/brianteeman/pen/qBQebWw

**Comment by nikosdion** [comment]
I know you can (we do something similar in FEF for multicolour selects), but I do not want to mess _too_ much with the SCSS at this point in time. I also need to think about whether it makes sense to use Bootstrap conventions versus my own classes, how it will work in Dark Mode (which is implemented with a class selector on the BODY element with Bootstrap), do I need to stick to the core Bootstrap colours or should I go for a more extended palette (using the warning / error colours may be problematic for semantic reasons) etc. 

It's doable, one way or another, but I would rather focus on more pressing issues at the moment.

I will re-open this ticket but mark it as a future item to think about.
