### ISSUE TITLE
backup date text

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#119]
Sorry I looked but couldnt work it out

![image](https://github.com/akeeba/panopticon/assets/1296369/de90b968-703d-4241-a29e-6e666faa3b34)

![image](https://github.com/akeeba/panopticon/assets/1296369/49911f9f-5c25-4815-8e00-cb86d48816ca)

**Comment by nikosdion** [comment]
The description comes partially from Akeeba Backup itself. We send the text "Remote backup taken on [DATE] [TIME]". This is how it's formatted by Akeeba Backup. This is better than the default of all other services which is just "Remote backup with XYZ service".

The others I know where they come from, I'll fix them.

**Comment by brianteeman** [comment]
But the [TIME] is formatted differently to the backups taken directly on the site or the cli

**Comment by nikosdion** [comment]
Are you confusing [TIME] and [TIME_TZ]? The former is what you see here, the latter has the time zone as well.

**Comment by brianteeman** [comment]
well i tried to change the message to TIME_TZ but that just added utc to the string it didnt change the format of the date to longform

**Comment by brianteeman** [comment]
yay - thanks

**Comment by nikosdion** [comment]
You're welcome! And thank you for helping me understand how this feature is likely to be used in the real world :)
