### ISSUE TITLE
joomla update

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#123]
strange 1st email says 

> Panopticon was unable to install the new Joomla! version 4.3.4 on your site “[Sinai Dev](https://dev.sinaileeds.uk/)”. The error received is as follows:

> The update extraction has failed; the site may be broken. Returned error message: “The archive is corrupt or truncated”

> Action required
The new version will NOT be installed automatically. You will have to install it yourself.

but then 1 minute later it says upgrade successful

![image](https://github.com/akeeba/panopticon/assets/1296369/3ee13a71-d7d1-4fdf-af61-47ad79c6e6ba)

**Comment by nikosdion** [comment]
Panopticon tries to download the update ZIP archive in two different ways.

One, using custom code which performs a chunk download from Joomla's mirror on CloudFlare CDN. This allows the update to work at all on a lot of servers where downloading from the primary mirror (a slow as heck Amazon S3 bucket in the US) consistently fails.

The second method is to let Joomla! Update do its thing.

The first method _may_ fail, e.g. when the server does something funky with HTTP caching, if an error occurs on CloudFlare's side, etc. In this case we detect the error and reschedule the update with the second method. That was the first email. Then the update proceeds with the second download method. That was the second email.

FWIW, I had 5 sites successfully updated overnight on a variety of hosting environments (local server, custom Ubuntu Server on Akamai formerly known as Linode, Rochen, CloudAccess). All of them worked with the first method. So, that method does work except, as I said, if an unexpected issue outside our software happens. Well, Brian, guess what? You ended up inadvertently testing the error condition that I suspected would happen on a minority of sites! It's your luck, man.

**Comment by brianteeman** [comment]
If I didnt have bad luck I would have no luck at all.

My report was more about the text in the first email

> The new version will NOT be installed automatically. You will have to install it yourself.

**Comment by nikosdion** [comment]
My focus was on getting the rescheduling to work, not to suppress the message. I am not sure if I can suppress the message; it's something I will be looking at.
