### ISSUE TITLE
Houston we have a problem

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#154]
[    require APATH_ROOT . '/version.php';](https://github.com/akeeba/panopticon/blob/1d876cc5bde478e6a8b6d7a507e3917758dad902/index.php#L16)

**Comment by brianteeman** [comment]
it is in the release file but not in github so a cloned install wont work

**Comment by brianteeman** [comment]
no i forgot - but then there wasn't an obvious readme in the repo to remind me. Not every expert will read the expert part of the wiki and will just dive in.

**Comment by nikosdion** [comment]
And done! Thank you :)
