### ISSUE TITLE
Error on setup on step index.php?view=setup&task=cron

### ISSUE THREAD

**Issue by webgobe** [akeeba/panopticon#157]
There was an unrecoverable error

The server returned the following error:

0 — Attempted to call function "iconv_strpos" from namespace "Symfony\Polyfill\Mbstring".

**Comment by nikosdion** [comment]
It looks like your server has neither the `mbstring` nor the `iconv` PHP extensions enabled. At least one of them —it does not matter which one— needs to be enabled.

Ask your host how to do that. Usually, there is a hosting control panel page where you can select which extensions to enable for each PHP version installed on your server.

Also worth noting, whenever you upgrade PHP you will need to make sure that the same PHP extensions are enabled in the new PHP version, ideally before making it the default. This applies for hosting of any PHP software, including Joomla! itself.

**Comment by webgobe** [comment]
Thanks, this worked!

**Comment by nikosdion** [comment]
You're welcome!
