### ISSUE TITLE
Administration - Log Files: Undefined property: Akeeba\Panopticon\View\Logs\Html::$itemsCount

### ISSUE THREAD

**Issue by PhocaCz** [akeeba/panopticon#158]
Hi,

in administration - log files:

Warning: Undefined property: Akeeba\Panopticon\View\Logs\Html::$itemsCount in src/View/Logs/Html.php on line 153

BTW: Akeeba Panopticon looks great!

**Comment by nikosdion** [comment]
Thank you very much! I refactored that code and forgot to change the method which retrieves the site names 🤦🏽‍♂️
