### ISSUE TITLE
Joomla! version support status

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#163]
Get the data from https://endoflife.date/api/joomla.json just like we do for PHP

Check the version family and report if it's end of life, in security update only, or actively supported — both in the Overview and the Site Information page.

If a version is newer than the latest version we have in the data, assume it's supported, but do not print any further information about it. If a version is older than the oldest version we have in the data, assume it's End of Life, but do not print EOL information.

If the patch version on the site is older than the patch version in the data, show a warning that the update information might be stale.

Report the date the version family goes into security updates only, and end of life in the Site Information page only.

Add a link to the data source (https://endoflife.date/joomla) in the Site Information page only.

**Comment by brianteeman** [comment]
cool service - never saw that before

**Comment by nikosdion** [comment]
It's one of the hidden gems :) They have a mix of automation and crowd-sourcing to get the version numbers and the dates.

**Comment by nikosdion** [comment]
Ultimately, I had to hard-code this information. Joomla! provides incomplete and conflicting information:

* https://docs.joomla.org/Joomla!_CMS_versions
* https://downloads.joomla.org
* https://developer.joomla.org/roadmap.html
* https://www.joomla.org/announcements/release-news/5868
* https://www.joomla.org/announcements/release-news/5900

There is actually no official information on whether Joomla! 4.4 will continue fixing bugs through October 17th, 2025, or whether (and when) it will become a security-only release. I have asked the release manager and hope to receive a semi-official response. Meanwhile, I am assuming it's one year of bug fixes and one year of security-only fixes, just like it happened with Joomla! 3, fully expecting that the bug fixes may only last for as little as 6 months.
