### ISSUE TITLE
getStatusCode() on null error on adding a Joomla 4 site

### ISSUE THREAD

**Issue by webgobe** [akeeba/panopticon#164]
Another issue: when adding  a new Joomla 4 site (I already have some) I get this error: Call to a member function getStatusCode() on null.  It's my own site, the Panopticon is whitelisted in admin tools as recommended, nothing obvious in site's logs.

**Comment by nikosdion** [comment]
Can you please give me a screenshot to better understand the context here?

**Comment by webgobe** [comment]
![Screenshot 2023-10-20 at 18-55-43 Akeeba Panopticon](https://github.com/akeeba/panopticon/assets/13080862/6b8b73cf-5952-4819-919a-69c655b6eacf)

**Comment by webgobe** [comment]
![Screenshot 2023-10-20 at 18-56-43 Akeeba Panopticon Connector - webGóbé - the craftsman of the WEB - Administration](https://github.com/akeeba/panopticon/assets/13080862/d93381bc-2c57-48e3-a17c-e6565b214362)

**Comment by webgobe** [comment]
![Screenshot 2023-10-20 at 18-57-41 Site IP Allow List - webGóbé - the craftsman of the WEB - Administration](https://github.com/akeeba/panopticon/assets/13080862/e051fb29-7c68-4537-b830-9fd6c7a7cc9c)

**Comment by nikosdion** [comment]
Please remember to redact your API key when posting screenshots, it is equivalent to Super User access on your site :) I deleted the screenshots with it, but please go to your user account and reset your Joomla API Token.

I will come back with detailed troubleshooting instructions for your issue shortly.

**Comment by webgobe** [comment]
Do you need any other info? Panopticon runs on PHP Version 8.2.11

**Comment by webgobe** [comment]
Hmm, how I can reset the API token? I did not found any way to do it.

**Comment by nikosdion** [comment]
Site backend. On the top right corner User Menu, Edit Account. Click on the Joomla API Token tab. Set Reset to Yes. Click on Save & Close. This tells Joomla! to reset the API token to a new, randomly generated one.

**Comment by webgobe** [comment]
Thanks, done

**Comment by nikosdion** [comment]
Please install this dev release: https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310201614.html (on top of your current installation).

Retry adding the same site. You will see a different error message. What does it read?

**Comment by webgobe** [comment]
![image](https://github.com/akeeba/panopticon/assets/13080862/97d7fb7a-4dfb-42be-9f15-3923632b5001)

**Comment by nikosdion** [comment]
I know it doesn't look like it, but that's progress! It means that we have an error with the Guzzle library I couldn't reproduce locally. Now we need it to tell us why exactly it threw an error. For this, I had to make yet another change and you need to install yet another dev release: https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310201638.html

After installing it, the error will change. It will appear in the middle of the page and will start with “The communication library used by Panopticon (Guzzle) has reported the following error:”. I need the next bit after that. That will be the actual error message from Guzzle.

**Comment by webgobe** [comment]
ok, give me a minute

**Comment by webgobe** [comment]
There was a communication error with your site.

The communication library used by Panopticon ([Guzzle HTTP](https://github.com/guzzle/guzzle)) has reported the following error:

Will not follow more than 5 redirects

This is an unexpected condition which may indicate a communication error we have not yet seen, a problem within Guzzle itself, a problem with the server you have installed Panopticon on, or a problem in Panopticon itself. Please search the open and closed issues [on our GitHub repository](https://github.com/akeeba/panopticon/issues?q=is%3Aissue). If nobody else has reported this, please open an issue and we will take a look.

**Comment by webgobe** [comment]
I am wondering, why is this, the domain is the main domain of the account, and the only redirect I see there is the forcing of HTTPS pages: 
![image](https://github.com/akeeba/panopticon/assets/13080862/92f42b55-9053-4089-bddd-b68131febf9b)

**Comment by webgobe** [comment]
There are multiple domains pointing to the site, so if where any other domain/addon domains in cause, I would suspect a redirection/DNS problem, but I think is not the case

**Comment by nikosdion** [comment]
First of all, you should be using `https://webgobe.com/api/index.php` instead of `https://webgobe.com/api`. Between that and the HTTP to HTTPS redirection you went over the limit of 5 redirections which confused the third party HTTP library. 

However, that's not the end of it. If you go to `https://webgobe.com/api/index.php` you will see that Joomla reports an internal server error which is basically a PHP error. This means that you have a third party plugin which is written badly, and does not take into account the existence of the API application.

The best thing you can do is try disabling one plugin at a time (I'd start with the `system` plugins, then move to the `webservices` plugins _except_ for those shipped with Joomla! itself). After disabling a plugin, retry accessing `https://webgobe.com/api/index.php`. Once you see the response `{"errors":[{"title":"Resource not found","code":404}]}` you will know that the last plugin you disabled was the one breaking the API application. Contact its developer and ask them to fix it.

**Comment by webgobe** [comment]
OK, will do. BTW, I already tried the trick with https://webgobe.com/api/index.php, but that does not help. On save is resetted to https://webgobe.com/api, the endpoint provided by the Panopticon component itself. But yes, trying the plugin deactivation trick makes perfect sense, the site was started as a Joomla 1.0.* site, and upgraded over years. I did some house cleaning time to time, but probably there is still dust accumulated in various corners ;) Will let you know as I found something, thanks for your help so far.

**Comment by webgobe** [comment]
hmm, at least one of culprits found. I had a plugin named Advancedredirect, disabled that, and now https://webgobe.com/api/index.php produces a completely different output. Can you check it, please! (Error level is set to maximum and debug is on, can't keep the site this way too long)

**Comment by webgobe** [comment]
Ah, BTW, the Panopticon added the site ;)

**Comment by webgobe** [comment]
So, this was the output with error level at maximum and debug set to On:
{"errors":[{"code":500,"title":"Internal server error","detail":"mysqli_sql_exception: Field 'new_url' doesn't have a default value in \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/Mysqli\/MysqliStatement.php:435\nStack trace:\n#0 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/Mysqli\/MysqliStatement.php(435): mysqli_stmt->execute()\n#1 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/DatabaseDriver.php(675): Joomla\\Database\\Mysqli\\MysqliStatement->execute()\n#2 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/Mysqli\/MysqliDriver.php(817): Joomla\\Database\\DatabaseDriver->execute()\n#3 \/home\/webgobec\/public_html\/plugins\/system\/redirect\/src\/Extension\/Redirect.php(250): Joomla\\Database\\Mysqli\\MysqliDriver->insertObject('#__redirect_lin...', Object(stdClass), 'id')\n#4 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/event\/src\/Dispatcher.php(486): Joomla\\Plugin\\System\\Redirect\\Extension\\Redirect->handleError(Object(Joomla\\CMS\\Event\\ErrorEvent))\n#5 \/home\/webgobec\/public_html\/libraries\/src\/Application\/EventAware.php(111): Joomla\\Event\\Dispatcher->dispatch('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#6 \/home\/webgobec\/public_html\/libraries\/src\/Application\/CMSApplication.php(320): Joomla\\CMS\\Application\\WebApplication->triggerEvent('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#7 \/home\/webgobec\/public_html\/api\/includes\/app.php(53): Joomla\\CMS\\Application\\CMSApplication->execute()\n#8 \/home\/webgobec\/public_html\/api\/index.php(31): require_once('\/home\/webgobec\/...')\n#9 {main}\n\nNext Joomla\\Database\\Exception\\ExecutionFailureException: Field 'new_url' doesn't have a default value in \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/Mysqli\/MysqliStatement.php:442\nStack trace:\n#0 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/DatabaseDriver.php(675): Joomla\\Database\\Mysqli\\MysqliStatement->execute()\n#1 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/database\/src\/Mysqli\/MysqliDriver.php(817): Joomla\\Database\\DatabaseDriver->execute()\n#2 \/home\/webgobec\/public_html\/plugins\/system\/redirect\/src\/Extension\/Redirect.php(250): Joomla\\Database\\Mysqli\\MysqliDriver->insertObject('#__redirect_lin...', Object(stdClass), 'id')\n#3 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/event\/src\/Dispatcher.php(486): Joomla\\Plugin\\System\\Redirect\\Extension\\Redirect->handleError(Object(Joomla\\CMS\\Event\\ErrorEvent))\n#4 \/home\/webgobec\/public_html\/libraries\/src\/Application\/EventAware.php(111): Joomla\\Event\\Dispatcher->dispatch('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#5 \/home\/webgobec\/public_html\/libraries\/src\/Application\/CMSApplication.php(320): Joomla\\CMS\\Application\\WebApplication->triggerEvent('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#6 \/home\/webgobec\/public_html\/api\/includes\/app.php(53): Joomla\\CMS\\Application\\CMSApplication->execute()\n#7 \/home\/webgobec\/public_html\/api\/index.php(31): require_once('\/home\/webgobec\/...')\n#8 {main}\n\nNext Exception: PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE in \/home\/webgobec\/public_html\/plugins\/system\/redirect\/src\/Extension\/Redirect.php:252\nStack trace:\n#0 \/home\/webgobec\/public_html\/libraries\/vendor\/joomla\/event\/src\/Dispatcher.php(486): Joomla\\Plugin\\System\\Redirect\\Extension\\Redirect->handleError(Object(Joomla\\CMS\\Event\\ErrorEvent))\n#1 \/home\/webgobec\/public_html\/libraries\/src\/Application\/EventAware.php(111): Joomla\\Event\\Dispatcher->dispatch('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#2 \/home\/webgobec\/public_html\/libraries\/src\/Application\/CMSApplication.php(320): Joomla\\CMS\\Application\\WebApplication->triggerEvent('onError', Object(Joomla\\CMS\\Event\\ErrorEvent))\n#3 \/home\/webgobec\/public_html\/api\/includes\/app.php(53): Joomla\\CMS\\Application\\CMSApplication->execute()\n#4 \/home\/webgobec\/public_html\/api\/index.php(31): require_once('\/home\/webgobec\/...')\n#5 {main}"}]}

**Comment by webgobe** [comment]
So, problem solved, thank you!

**Comment by nikosdion** [comment]
Awesome! I am glad I could help :)
