### ISSUE TITLE
how update works

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#166]
hi, i'm trying panopticon on several sites ( about 15) and on some circumstances some updates not happens:
1 site with the plugin regular labs 
1 site with components icagenda

the panopticon tell me that component will be updated automatically but nothing happens..
maybe in a future release implement a button to " update all" or "update selected"

**Comment by nikosdion** [comment]
This is a known issue, already fixed in the latest dev release: https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310231224.html

Please install this dev release and the extension updates will start working again.
