### ISSUE TITLE
error on only 1 website

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#167]
i receive this error when i try to enter/configure one of my websites

0 — Awf\Container\Defaults\DateFactoryProvider::Awf\Container\Defaults\{closure}(): Argument #1 ($date) must be of type string, null given
[View template: ROOT/tmp/compiled_templates/f20408764ed5d97da68e92598d5e69a1b7426407.php line 31, compiled from ROOT/ViewTemplates/Sites/item_backup.blade.php]

**Comment by nikosdion** [comment]
Thank you! Confirmed and fixed.
