### ISSUE TITLE
Add TOTP as an alternative MFA method

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#168]
can you pls add tf2a authentication like totp and not only passkey
thanks :)

**Comment by nikosdion** [comment]
I have already been thinking about adding TOTP, i.e. the six-digit codes which change every 30 seconds. This is a good method to use as a backup, until passkey sharing across device ecosystems becomes a reality.

I will change the title of this ticket to better reflect the actionable item.

**Comment by nikosdion** [comment]
As you can see, your wish is granted 😉 

Have a great evening!

**Comment by nikosdion** [comment]
You're welcome!
