### ISSUE TITLE
No mail type for  'Unable to upgrade “[SITE_NAME]” to Joomla!™ [NEW_VERSION]'

### ISSUE THREAD

**Issue by ChrisHoefliger** [akeeba/panopticon#172]
On editing mail templates I find that there is no mail type for above mail. I wanted to translate all templates, and got stuck there.
![Screenshot 2023-10-24 123326](https://github.com/akeeba/panopticon/assets/2324829/82e0502c-1702-4395-8445-ea6feff0d916)
Apart from this this app works beautiful for me. I hope there will be more soon!

**Comment by nikosdion** [comment]
Thank you! There was a missing line in [src/Model/Mailtemplates.php](https://github.com/akeeba/panopticon/commit/cfc8dc4763eb03d7495a3c7b15e999f5f2afc434#diff-111fe415ccf043f8de8fb575f13942b295c167e4738f23b46b687b38672836d9). If you add it, as seen in green in the link above, you will be able to edit this template just fine.

**Comment by ChrisHoefliger** [comment]
Thx very much indeed.

**Comment by nikosdion** [comment]
You're welcome!
