### ISSUE TITLE
Nothing happens after setting up CRON job

### ISSUE THREAD

**Issue by Scrabble96** [akeeba/panopticon#175]
I have set up a new domain for Panopticon which runs on PHP 8.2 and all pre-checks were passed. I double-checked the path/to/php with my hosts and confirmed that that /usr/bin/php is the correct path for CLI executable. I successfully set up the correct CRON job to run every minute. Nothing happened so I contacted my hosts and they confirmed that the CRON job is running every minute. They gave me a screen dump showing it is running every minute; an edited version to remove my URL is shown below:

Oct 24 16:19:02 katla-lon CROND[2465510]: (myaccount) CMD (/usr/bin/php /home/myaccount/panop.mydomain.co.uk/cli/panopticon.php task:run --loop >/dev/null 2>&1)
Oct 24 16:20:05 katla-lon CROND[2467464]: (myaccount) CMD (/usr/bin/php /home/myaccount/panop.mydomain.co.uk/cli/panopticon.php task:run --loop >/dev/null 2>&1)

Back on the domain at mydomain/index.php?view=setup&task=cron, the setup page has not changed, so I cannot proceed.

So, I tried the wGET option instead (I use wGET for Akeeba backups). Same result - nothing changes on the installation/setup page. But if the first CLI CRON job is running, why isn't it working on the domain?

**Comment by nikosdion** [comment]
When you run the installer, just before it displays the CRON page, it installs the `maxexec` task. So, first check the table `pnptc_tasks` for a row whose `type` column has the value `maxexec`. Does it exist?

The task updates two records in the `pnptc_akeeba_common` table whose keys are `maxexec.lasttick` and `maxexec.done`. Do these exist? If so, what are their values?

**Comment by Scrabble96** [comment]
pnptc_tasks has one row and yes, the 'type' column has the value 'maxexec' in this row.

pnptc_akeeba_common - there are only two keys: mail.common_css and panopticon.task.last.execution

**Comment by nikosdion** [comment]
At the bottom of the page in Panopticon (you may have to scroll all the way down) there is a button title “Skip this step (not recommended)”. Click on it.

Do you get a message that the CRON jobs are not running? If you do, the CRON jobs do not actually run. 

If you don't see this message, that's great! Go to Administration, System Configuration and set the “Maximum Execution Time” to whatever your host tells you is the CPU time limit cap (`ulimit -t`) of your account, or 180 — whichever is smaller. If the host cannot give you that information set it to 90 and pray they didn't withhold this information because they are absurdly restrictive.

**Comment by Scrabble96** [comment]
Hi. I skipped the step and now have an 'Add a Site' window.

**Comment by nikosdion** [comment]
Good! Try to add a site.

Check the main page (Overview) two minutes after adding the site. If it does not complain about the CRON jobs you're golden.

**Comment by Scrabble96** [comment]
Hooray! One test site added and it's found all the extensions I have installed.

**Comment by nikosdion** [comment]
Awesome 🙌🏻

**Comment by Scrabble96** [comment]
And now it tells me that I should update from 4.3.4 to 4.4.0. Thank you for your help. I might try switching back to CLI from wGET and see what happens. I'll be checking about 15, small sites in all, eventually.

**Comment by nikosdion** [comment]
I am glad I could help 😄 Have a great evening!

**Comment by Scrabble96** [comment]
And I've just updated to 4.4.0 from Panopticom control panel. Thanks again. You have a good evening, too.

**Comment by nikosdion** [comment]
You're welcome!
