### ISSUE TITLE
Updates Overview page

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#178]
Display all extension updates found across all sites, with the option to select which updates to schedule for update.

Filter by extension name, site, author, author URL, author email, installed version, new version.

**Comment by nikosdion** [comment]
You will be able to select all with a single click, just like all grid views in Panopticon. So, two clicks to update all instead of one. Minimum added burden for maximum added peace-of-mind. Mistakes are easy to make when there's only button to click. Ask me how I know…

**Comment by Martin511** [comment]
It would be nice if this were implemented in exactly the same way for the Joomla Core updates and not just for extensions.

**Comment by Martin511** [comment]
> maybe i'm dumb but i can't find where with a click i can update all :(

It is not implemented yet.

**Comment by nikosdion** [comment]
It was a fair ask, it's now implemented.

Have a wonderful evening, folks, and thank you for you feedback!
