### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#180]
In the newly merged PR you use terminology that just doesnt read right to me.

> The selected extension has been scheduled for update installation.

The use of update and installation together may be confusing as within Joomla we normally refer to an install or an update. And yes I realise and update is installed but in this case we could consider "installation" to be a superfluous word. 

Can I suggest you consider one of the following alternatives

> The selected extension has been scheduled for update.

> The selected extension has been scheduled to be updated.

or perhaps you have another idea

**Comment by nikosdion** [comment]
No, I agree with you. Go ahead and make a PR with the terminology change.

**Comment by brianteeman** [comment]
ok - will do.
