### ISSUE TITLE
what version am i?

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#183]
version.php is only generated when you run composer install - as a result if you update via git alone your version number is never incremented. Suggestion to commit version.php to the archive and move makeVersionPhp to your release scripts

releasenotes.md - there is no version number in the release notes

**Comment by nikosdion** [comment]
This file must never be committed. Every time I run composer update or phong git it gets generated. It would end up polluting the commits with hundreds of meaningless changes. 

Every time you git pull you MUST run composer install. I update dependencies in both Composer and NPM all the time. 

The release notes must not have a version number. They are copied verbatim to the GitHub release which is against a versioned tag which is displayed right above the release notes. Having the version in the release notes makes for a very weird presentation.

**Comment by brianteeman** [comment]
Guess we will have to agree to disagree on this then

**Comment by nikosdion** [comment]
It's not a matter of disagreement or agreement. It's a matter of objective reality.

The `version.php` in your scenario would have to contain the _actual_ version represented by the repository's state. 

If you do a `composer update` you'll see that it creates a dev release number which includes the latest commit hash. **THIS** is the version you are on at any given time. You cannot know the commit hash before you commit. 

Therefore, not only we would burden the development and unnecessarily inflate the size of the Git data by committing a new `version.php` file with every commit, the `version.php` file committed would also be **objectively wrong** as it would not represent the actual state of the repository and you would still need to run `composer update` not only to update the wrong `version.php` file, but also to pull dependencies.

Speaking of, have you ever considered why we only include the `composer.lock` file and not the entire `vendor` folder? Look it up. It will give you some perspective on development best practices.
