### ISSUE TITLE
an unrecoverable error

### ISSUE THREAD

**Issue by Philippe-FRICH** [akeeba/panopticon#187]
Nicholas
To try Panopticon, I just registered around fifty Joomla sites.
For the most part everything is going well, but for 6 of them it is impossible to access their status.
a beautiful red page appears with the message:
There was an unrecoverable error
The server returned the following error:
0 — Akeeba\Panopticon\Model\Sysconfig::isExcludedShortname(): Argument #1 ($shortname) must be of type string, null given, called in /home/chatrunc/public_html/chatloupe/panoptique/tmp/compiled_templates/49956f2fb4f44e4d4630d88ffb6ed317b776206c. php on line 77
[View template: ROOT/tmp/compiled_templates/49956f2fb4f44e4d4630d88ffb6ed317b776206c.php line 35, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php]

If I delete the file 49956f2fb4f44e4d4630d88ffb6ed317b776206c.php it reappears with the same error

**Comment by nikosdion** [comment]
This means that you have an extension on those sites which is not a component, file, library, package, plugin, module, or template extension. However, these are all of the Joomla! extension types. It sounds like they were either originally cloned from the same problematic site, or someone was messing with the `#__extensions` table on those sites.

Can you please try [this dev release](https://www.akeeba.com/download/panopticon-dev/1-0-2-dev202310270946.html) and tell me if it works for these sites?

**Comment by Philippe-FRICH** [comment]
Hi Nicholas
I just installed dev version 1.0.2 and I still have the same problem.

**Comment by nikosdion** [comment]
Did you remove the `tmp/compiled_templates` folder after installing the development release?

If you did, please paste the actual error message you get. I can tell you it cannot possibly be the same since the view template has changed, therefore you cannot possibly get the same line reference.

**Comment by Philippe-FRICH** [comment]
Hi Nicholas
My version is Panopticon of Akeeba 1.0.2.dev202310270946
I deleted tmp/compiled_templates
I cleared my browser cache, I even changed browsers and I still get:
There was an unrecoverable error
The server returned the following error:

0 - Akeeba\Panopticon\Model\Sysconfig::isExcludedShortname(): Argument #1 ($shortname) must be of type string, null given, called in /home/chatrunc/public_html/chatloupe/panoptique/tmp/compiled_templates/49956f2fb4f44e4d4630d88ffb6ed317b776206c.php on line 77
[View template: ROOT/tmp/compiled_templates/49956f2fb4f44e4d4630d88ffb6ed317b776206c.php line 35, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php]

**Comment by nikosdion** [comment]
Try using this https://www.akeeba.com/download/panopticon-dev/1-0-2-dev202310291236.html

**Comment by Philippe-FRICH** [comment]
the error disappeared with this version
THANKS
