### ISSUE TITLE
Akeeba Panopticon - Edit Avatar

### ISSUE THREAD

**Issue by aboarken** [akeeba/panopticon#190]
Hello Nicholas,

There is an issue when I try to click on "edit the avatar" picture. Please check the below images:

![Screenshot_1](https://github.com/akeeba/panopticon/assets/18500882/bc4f23f2-149b-405d-b344-9cef358c058b)

![Screenshot_2](https://github.com/akeeba/panopticon/assets/18500882/64861988-01c0-4381-a3c1-67106f08918c)

**Comment by nikosdion** [comment]
Not an issue with Panopticon. You need to be logged in to the **THIRD PARTY SERVICE** (look at the URL) for that link to work.

**Comment by aboarken** [comment]
@nikosdion, I apologize for my silly question.
