### ISSUE TITLE
error on edit profile

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#193]
When i edit my user profile (debug maximum)
Deprecated: Awf\Text\Text::script is deprecated. Use the document's lang() method instead. in /home/u123184p119539/domains/itics.nl/public_html/webmon/vendor/akeeba/awf/src/Text/Text.php on line 496

Deprecated: Calling Awf\Application\Application::getInstance is deprecated. Go through the Container instead. in /home/u123184p119539/domains/itics.nl/public_html/webmon/vendor/akeeba/awf/src/Application/Application.php on line 131

**Comment by nikosdion** [comment]
This is already fixed for 1.0.2.
