### ISSUE TITLE
feature request: add multiple 2FA options

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#194]
Currently only webkey is available for 2FA. Can you add 2FA using authenticator to the options.

**Comment by johanpeters** [comment]
and if possible set general 2FA (forced) so that every account need to set 2FA before getting access. 
same way as you build Akeeba 2FA

**Comment by nikosdion** [comment]
Duplicate of https://github.com/akeeba/panopticon/issues/168

Already implemented for 1.0.2
