### ISSUE TITLE
feature request: IP security

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#195]
Add a option to only allow access to panopticon from specific IP addresses.

**Comment by nikosdion** [comment]
There is no point doing what you can easily do with Apache. Reference: https://htaccessbook.com/access-control-apache-2-4/ 

Remember, Panopticon does not have a public part. That's the only reason why IP-based access control in Joomla! and WordPress requires doing it at the application-level: we cannot convey the login context to the web server.
