### ISSUE TITLE
error when login /logout / and manage account

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#199]
updated to 1.0.2 
this error pops up 

            $this->setRedirect($url);
        }
        catch (Exception $e)
        {
            $logger->error('Failed login', [
                'username' => $username, 'error' => $e->getMessage(), 'source' => $e->getFile() . ':' . $e->getLine(),
            ]);
            $router = $this->container->router;

vendor\/monolog\/monolog\/src\/Monolog\/Handler\/StreamHandler.php:134

**Comment by nikosdion** [comment]
You are missing the actual error message. Can you please paste it?

**Comment by nikosdion** [comment]
Don't overwrite users.php because you are reintroducing the security issue I fixed in 1.0.2. Your problem actually has to do with what I fixed here: https://github.com/akeeba/panopticon/commit/69465c8afa693886bf76713cbca29ab7e7c500db
