### ISSUE TITLE
Even if I clear cache/self_update Panopticon doesn't display the 1.0.2 update

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#200]
I am currently using Panopticon 1.0.1 and the cache/self_update folder was already empty, unfortunately Panopticon does not display the new update available to 1.0.2.

How can I manually install the update? Would it be enough to unzip the ZIP package in the root directory?

**Comment by nikosdion** [comment]
Yes, you can unzip the file on top. That's what the updater does: it download the new version's ZIP file to your server and unzips it on top of the exiting installation.
