### ISSUE TITLE
Extension & core updates - There was an unrecoverable error

### ISSUE THREAD

**Issue by Philippe-FRICH** [akeeba/panopticon#201]
Hi
I have just installed V1.0.2 and when I click on "extension updates", I obtain a red page with the instructions:
There was an unrecoverable error
The server returned the following error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.extensions.hasUpdates' = 1' at line 3

and when I click on "core updates", I obtain a new red page with the indications:
There was an unrecoverable error
The server returned the following error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.core.current.version' IS NOT NULL AND `config`->'$.core.latest.version' I...' at line 3

**Comment by nikosdion** [comment]
What's your MariaDB version?

If unsure, check your hosting control panel.

If that is not listed there, ask your host.

**Comment by Philippe-FRICH** [comment]
my version of MariaDB is 10.5.21

**Comment by Martin511** [comment]
> my version of MariaDB is 10.5.21

Same issue here.
I have MariaDB 10.5.22

**Comment by nikosdion** [comment]
Good. That clarifies a few things.

MariaDB's documentation, unlike the MySQL documentation, is not versioned. They don't actually mention which version of MariaDB introduced JSONPath expressions. They only say they were improved in 10.9 (the current stable MariaDB version is 11.1, by the way). At the same time, they offer releases which are supported for quite a number of years BUT I don't have access to all of them (nor would I be insane enough to test against all of them; there are currently _ten_ supported releases). To make matters worse, some hosts only offer an LTS originally released a decade ago, making it super-extra hard to determine which features are actually supported in which version of MariaDB.

I guess we can safely say JSONPath expressions are not supported in MariaDB 10.5 and earlier. I'll work around it.

**Comment by johanpeters** [comment]
currently i have 

10.4.27-MariaDB
--
i will ask my hoster to update 


<br class="Apple-interchange-newline">

**Comment by nikosdion** [comment]
@johanpeters Even if they don't, I have a workaround in place for 1.0.3 :)

**Comment by johanpeters** [comment]
> @johanpeters Even if they don't, I have a workaround in place for 1.0.3 :)

create.. hoster will not update soon. only option is to move everything to a other server with later version.
that requires a new subscribtion and to move everything i have myself or the can do it for me, pay'd ofcourse..

**Comment by nikosdion** [comment]
And stuff like that is why today I spent some time to collect the PHP and MySQL/MariaDB versions y'all are using. It is extra difficult deciding what should be the minimum ancient, barely supported version of PHP, MySQL, and MariaDB a hosting company decided to inflict upon you if I don't have some hard evidence.

BTW, not to worry, this is all anonymous, you can opt out, and it's collected using the same framework we've been using in our other products the last decade. I only keep an aggregate. What I see is this: X% of all users of software Y in month Z used MariaDB version a.b.c. Plotting that over time I can understand how different hosts deal with updating their base software and make informed decisions.
