### ISSUE TITLE
Unrecoverable Error while Accessing my Profile

### ISSUE THREAD

**Issue by aboarken** [akeeba/panopticon#212]
Hello Nicholas,

Please be informed that I have upgraded Akeeba Panopticon to the latest version 1.0.2. When I have successfully logged in then tried to access 'My Profile', it gave me the following error as shown also in the attached picture:

There was an unrecoverable error
The server returned the following error:
403 - Access Denied

![Screenshot](https://github.com/akeeba/panopticon/assets/18500882/8847808f-e203-4d94-866f-3a353f2b9f36)

How to fix this issue please.

Regards, Ahmad

**Comment by Philippe-FRICH** [comment]
Same with MariaDB v10.5.21
