### ISSUE TITLE
extention update error

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#213]
on extention update i get errors 

1 Nov 23 07:40:21 CET | Error | Extension updates for site #5 (donmuschter): failed installing update for component “AcyMailing”. Guzzle error: Client error: `POST https://websiteurl.com/panopticon_api/index.php/v1/panopticon/update` resulted in a `404 Not Found` response: {"errors":[{"title":"Resource not found","code":404}]}
-- | -- | --

this is on all extentions on multiple site's.. ps . are Joomla 3.12 site's.
also 2 sites Joomla 3.12 its working.. so its not a structual issue regarding joomla 3.x

**Comment by nikosdion** [comment]
Try changing your Endpoint URL from `https://www.example.com/panopticon_api/index.php` to `https://www.example.com/index.php/panopticon_api`. Did that work for you?

**Comment by johanpeters** [comment]
hello @nikosdion i have changed the endpoint url, but get the same result  / error.
i posted the joomla message seperately because of diverent error message.

OS and extention update failed on 2 servers.. other servers are fine and updated.

**Comment by nikosdion** [comment]
When you click the reload button next to the Joomla! version, and the reload button next to the extensions, do you get any errors?

**Comment by nikosdion** [comment]
Do you have any plugins which deal with SEO, or redirections (NOT Admin Tools; I know Admin Tools does not interfere) on that site?

**Comment by johanpeters** [comment]
> Do you have any plugins which deal with SEO, or redirections (NOT Admin Tools; I know Admin Tools does not interfere) on that site?

no additional SEO or other redirects than core Joomla SEF.

**Comment by nikosdion** [comment]
Two more questions. Do you have any redirects in your .htaccess, e.g. from non-www to www or vice versa? If you do, are you using the final domain in your Endpoint URL?

What I mean is this. If you visit akeeba.com you are redirected to www.akeeba.com. If I were to use akeeba.com (without www) in my Endpoint URL it wouldn't work because the redirection will cause some of the data being sent to be lost in the process.

**Comment by johanpeters** [comment]
default htacces without any redirects 
i already tried with and without www.

**Comment by nikosdion** [comment]
Can you send me the exact error you are getting now?

**Comment by johanpeters** [comment]
> Can you send me the exact error you are getting now?

for some reason it works now.. joomla update and extension update's.. perhaps some kind of caching issue.. 
only issue i have now is unable to add 1 J3 site..  i will investigate more.. and report it back in a new issue .
