### ISSUE TITLE
Joomla update error

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#214]
joomla update 3.10.11 -> 3.10.12 is stuck with this error below

The update was scheduled to run automatically but ran into an error: Threw exception

The error reported was:

Client error: `POST https://leisuretravelmedia.com/panopticon_api/index.php/v1/panopticon/core/update/download` resulted in a `404 Not Found` response: {"errors":[{"title":"Resource not found","code":404}]}

**Comment by nikosdion** [comment]
I believe this is the exact same thing as https://github.com/akeeba/panopticon/issues/213

**Comment by johanpeters** [comment]
hello @nikosdion result is the same but error message is deferent.. thats why i posted 2 seperate issues.

**Comment by nikosdion** [comment]
You actually get the same error. You get a 404 from the API. The underlying reason is the same. I'll keep the conversation on the other issue to make sure everything is discussed in the same place.
