### ISSUE TITLE
feature: check status httacces / reminder

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#219]
regarding renaming httaccess.txt would it be handy to have this checked and if not renamed then after login you get a notify regarding this.
using httaccess.txt is partly recommended regarding security.

**Comment by nikosdion** [comment]
There's a reason this has not been implemented. It depends on whether you are using a web server which support this file (Apache or LiteSpeed), and whether you have already applied these settings in your virtual host configuration at the web server configuration level. This context cannot be gathered, therefore such a warning would be wrong for a fairly large proportion of sites.
