### ISSUE TITLE
feature request: posponing updates

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#221]
for some websites i use to suspend updates to prevent some last bugs of compatible issues.
would be create to have a posponing feature (time delay) for updates.

settings regarding Joomla updates, 
settings regarding joomla extentions in general and/or extention specific

and to make it complete, minor, major updates seperated to be configerd.

**Comment by nikosdion** [comment]
This is the use case of the extension updates overview and site updates overview pages I have created for 1.0.3. 

You set the update action to None or Email, then you go into that page and install whichever updates you want whenever you are ready.
