### ISSUE TITLE
New install of 1.0.2 didn't trigger setup

### ISSUE THREAD

**Issue by peachesandcorn** [akeeba/panopticon#225]
Grabbed the 1.0.2 release zip, and extracted it. On first accessing the site, instead of the setup page I was greeted with the login page. Couldn't login (obviously) or reach the setup view. Installing using the 1.0.1 release, then upgrading worked fine.

**Comment by nikosdion** [comment]
Yup, this is a known issue I've already fixed, see https://github.com/akeeba/panopticon/commit/7d708c412be09a685db01e849a39c8ab694f9c81
