### ISSUE TITLE
Check the API level of the installed connector

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#23]
If the installed connector is at an API level before what we support warn the user to update it.

Furthermore, we should only present features which are supported by the connector version in use.

This is obviously only relevant once we have a public version and after we need to update the connector to add new features. Until then, there is no need for this. New connector versions will remain b/c. If they have to change in a non-b/c manner their endpoint version will be bumped.

**Comment by ChrisHoefliger** [comment]
I ask myself why the connector has to be a component (that appears in the backend's component menu). If it were a plugin, there would be much less danger that a layman customer (who needs a super user account) would start playing around with the two entries in there, thus breaking the connection to panopticum.
Just a thought.

**Comment by nikosdion** [comment]
@ChrisHoefliger It's both a component and a plugin because this is how the Joomla API application works. The `webservices` plugin only defines the routes. The actual API calls have to handled by a component. Components _must_ always have an administrator section (the site and api sections are the only optional sections), which is why we have an admin section for the components. If you have a component, it also has to get a components menu item because that's how Joomla! works ever since components were introduced back when it was called Mambo.

**Comment by nikosdion** [comment]
This applies on a case-by-case (or, rather, feature-by-feature) basis. It does not need to be a separate issue.
