### ISSUE TITLE
missing mail templates

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#230]
Missing some of the mail templates.
using version 1.0.2 not al the mail templates are available.
only core joomla updates, Joomla updates and backup mail templates.
the templates regarding extentions are not available.

i know i can create new templates and assign them to the correct type of mail.
but the content of the mail, mainly the correct syntax for system information / extention information is not available so i can not create a specific template with the content .. only a general mail messages that a update is available.

**Comment by nikosdion** [comment]
This has already been fixed.
