### ISSUE TITLE
Login screen instead of installer

### ISSUE THREAD

**Issue by idefax** [akeeba/panopticon#231]
I did install Panopticon on a new subdomain. After I did open the URL to it. Instead of the installer I get the login screen.

## Reproduction instructions
added a new subdomain
downloaded and extracted panopticon-1.0.2.zip locally
transferred (ftp) the files to the new subdomain
opened the URL to subdomain in browser
==> I see the login screen

## Expected behaviour
Access to install screen.

## Environment
 - Panopticon version: 1.0.2
 - PHP version: 8.2
 - Database: 10.5.22-MariaDB 
 - Browser: Firefox, Chrome, Edge
 - Browser version: latest

**Comment by nikosdion** [comment]
This has already been fixed.
