### ISSUE TITLE
overview use of tags in mail messages

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#232]
Add in the mail editor een picklist of possible system variables that can be used.
currently you need to know what tags are usable to make the content of the message smart.

would be nice to have a picklist or overview of possible variables to use, sorted by the type of message.

**Comment by johanpeters** [comment]
i have seen the wiki pages.. integrating that specific part inside the editor / panopticon would be easier for the user the use the variables

**Comment by nikosdion** [comment]
It is really difficult to convey all the necessary information with language strings, that's why this is not and will not be implemented.
