### ISSUE TITLE
mail variable [SITE] not working

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#238]
mail variable [SITE] is not translated to the name of the site configered in panopticon.
in the mail message it just display's the variable and not the value 

[SITE_URL] is working and shows the value.

the other viariables (extention update found) are al working.

**Comment by nikosdion** [comment]
The variable name you are looking for is `[SITE_NAME]`, not `[SITE]`.

**Comment by johanpeters** [comment]
okay.. please change the wiki page regarding this toppic on extention update's.
currently it says [SITE] and not [SITE_NAME]

**Comment by brianteeman** [comment]
I have made that update
