### ISSUE TITLE
unrecovarable error extentions overview Panopticon v1.0.3

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#240]
when i try to access Overview - Extention updates i get the following error.

There was an unrecoverable error
The server returned the following error:

0 - Call to a member function authorise() on null
[View template: ROOT/tmp/compiled_templates/1b41c6f522eebbfb94f48ff8aee6570768ac30e4.php line 331, compiled from ROOT/ViewTemplates/Extupdates/default.blade.php]

**Comment by johanpeters** [comment]
> This means that you are logged out, but in this case how can you possibly go to this page?
> 
> Try logging out and back in.

did not solve the issue.. i am logged in .. core joomla overview page is working fine.. extentions overview not.

**Comment by nikosdion** [comment]
Cannot reproduce. Please provide accurate reproduction instructions.

**Comment by nikosdion** [comment]
I cannot reproduce your issue using your instructions. I have a list of extension updates.

<img width="1143" alt="Screenshot 2023-11-06 at 21 44 06" src="https://github.com/akeeba/panopticon/assets/256041/cb394397-3eb3-41ef-91dc-fcc003747d99">

**Comment by johanpeters** [comment]
perhaps MariaDB version issue.. or should that be resolved in version 1.0.3?

looks greate and what i expacted.. i will try to see if i can get more debug information

**Comment by nikosdion** [comment]
Do you have any extensions which do not have a Download Key set up but do have updates available?
