### ISSUE TITLE
Erron when click on My Profile in 1.0.3

### ISSUE THREAD

**Issue by Martin511** [akeeba/panopticon#242]
When I click on "My Profile", I get an error: Access Denied HTTP 500 Runtime Exception
Text:
"If you have a paid subscription and would like to get help for an error please print the page into a PDF file. Attach the PDF file to your support request. Do remember to tell us exactly what you were doing when the error occurred. "

 - Panopticon version: 1.0.3 - 
 - PHP version: 8.2
 - Database type: MariaDB

**Comment by nikosdion** [comment]
Duplicate https://github.com/akeeba/panopticon/issues/241

Please, always check closed issues before submitting yours.
