### ISSUE TITLE
unrecoverable error when trying to update from 1.0.2 to 1.0.3

### ISSUE THREAD

**Issue by brainyNL** [akeeba/panopticon#260]
Updating from v1.0.2 to v1.0.3 is not possible. 
Error: 
There was an unrecoverable error
The server returned the following error:

0 - Awf\Html\Helper\Basic::date(): Argument #1 ($input) must be of type string, DateTime given, called in /home/USER/domains/\DOMAIN/public_html/tmp/compiled_templates/5eb82faec9e00f4f1dbb9d67e58412269f15fa74.php on line 57
[View template: ROOT/tmp/compiled_templates/5eb82faec9e00f4f1dbb9d67e58412269f15fa74.php line 93, compiled from ROOT/ViewTemplates/Selfupdate/default_update.blade.php]

## Reproduction instructions

Step by step instructions to reproduce the behaviour:
1. Open [Panopticon] Go to 'Overview - Sites Overview'
2. You wille see: Panopticon 1.0.3 is available
3. Click on 'More information'
4. Now you will get the error 
5. See error

## Expected behaviour
Getting information and option to update.

## Screenshots
![image](https://github.com/akeeba/panopticon/assets/86366984/cf5b8381-42f4-4849-a755-8c460bfeaa88)

## Environment (please complete the following information)
 - Panopticon version: 1.0.2
 - PHP version:  8.2.11 
 - Database type: MariaDB
 - Database version: Serverversie: 10.4.31-MariaDB - MariaDB Server - Protocolversie: 10
 - Browser Chrome
 - Browser version Versie 119.0.6045.105 (Officiële build) (64-bits)

## Additional context
-

**Comment by nikosdion** [comment]
Already fixed in 1.0.3

**Comment by brainyNL** [comment]
But how should I update if the function (button) is not working?

**Comment by nikosdion** [comment]
If only I had documented [how you can do manual updates](https://github.com/akeeba/panopticon/wiki/Updates#manual-update). Wait… I have! 😉
