### ISSUE TITLE
Error when trying to open menus: Extension Updates and Core updates

### ISSUE THREAD

**Issue by brainyNL** [akeeba/panopticon#261]
## Describe the bug

Getting errors when opening the menu;s Extension Updates and Core updates
Sites overview is working fine

## Reproduction instructions

Step by step instructions to reproduce the behaviour:
1. Go to menu 'Overview'
2. Click on 'Extension Updates'  /and-or/ 'Core updates'
3. See error in print screen below

## Expected behaviour
Getting the views with Extension Updates and Core updates

## Screenshots
EXTENSION: 
![image](https://github.com/akeeba/panopticon/assets/86366984/f399f379-4fa7-412c-8045-bf1e998fc125)

CORE:
![image](https://github.com/akeeba/panopticon/assets/86366984/d02293c2-a810-4f02-83eb-8d2c36c255ba)

## Environment (please complete the following information)
 - Panopticon version: 1.0.2
 - PHP version: 8.2.11
 - Database type MariaDB

 - Database version: Serverversie: 10.4.31-MariaDB - MariaDB Server - Protocolversie: 10
Apache/2
Cliëntversie van database: libmysql - mysqlnd 8.1.24
PHP-uitbreiding: mysqli Documentatie curl Documentatie mbstring Documentatie sodium Documentatie
PHP-versie: 8.1.24
phpmyadmin Versie-informatie: 5.2.1 (meest recent)

 - Browser Chrome
 - Browser version Versie 119.0.6045.105 (Officiële build) (64-bits)

## Additional context
-

**Comment by nikosdion** [comment]
Already fixed in 1.0.3
