### ISSUE TITLE
1) Error in Cron log, 2) error when Overview > Extension updates is opened

### ISSUE THREAD

**Issue by EricdeWaal** [akeeba/panopticon#270]
1) webcron.log log: Error Task failed with exception type TypeError [/usr/www/users/prachta/updater/src/LibraryEntry in /Task/SymfonyStyleAwareTrait.php:18]: Akeeba\Panopticon\Task\MaxExec::setSymfonyStyle(): Argument #1 ($ioStyle) must be of type Symfony\Component\Console\Style\SymfonyStyle, null given, called in /usr/www/users/prachta/updater/src/Model/Task.php on line 427

2) Overview > Extension updates causes an error:
Call to a member function authorise() on null
[View template: ROOT/tmp/compiled_templates/983fb20d7e4b3bd0a8096c2e7bcab622e8ab52df.php line 331, compiled from ROOT/ViewTemplates/Extupdates/default.blade.php]

Stack trace:
 at /usr/www/users/prachta/updater/tmp/compiled_templates/983fb20d7e4b3bd0a8096c2e7bcab622e8ab52df.php:331
  at Awf\Mvc\View->handleViewException()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/View.php:1229)
  at Awf\Mvc\View->processTemplate()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/View.php:739)
  at Awf\Mvc\View->loadAnyTemplate()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/View.php:632)
  at Awf\Mvc\View->loadTemplate()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/View.php:554)
  at Awf\Mvc\View->display()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/Controller.php:442)
  at Awf\Mvc\Controller->display()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/Controller.php:452)
  at Awf\Mvc\Controller->main()
     (/usr/www/users/prachta/updater/src/Controller/Extupdates.php:29)
  at Akeeba\Panopticon\Controller\Extupdates->main()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Mvc/Controller.php:370)
  at Awf\Mvc\Controller->execute()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php:120)
  at Awf\Dispatcher\Dispatcher->dispatch()
     (/usr/www/users/prachta/updater/src/Dispatcher.php:36)
  at Akeeba\Panopticon\Dispatcher->dispatch()
     (/usr/www/users/prachta/updater/vendor/akeeba/awf/src/Application/Application.php:222)
  at Awf\Application\Application->dispatch()
     (/usr/www/users/prachta/updater/src/Application.php:264)
  at Akeeba\Panopticon\Application->dispatch()
     (/usr/www/users/prachta/updater/index.php:34)
  at {closure}()
     (/usr/www/users/prachta/updater/index.php:37)

**Comment by nikosdion** [comment]
Please submit separate issues. Issues are meant to be singular, actionable items. Do not mix two or more _unrelated_ items in the same issue. Mixed issues are impossible to efficiently triage, schedule, and track.

Remember to provide all of the requested information. Issues without the requested information cannot be acted upon.

Please make sure the issue you are reporting is not already reported and/or fixed. Always check the closed issues, not just the open ones. Duplicate issues, especially those filed for already resolved problems, take up time which would otherwise go into improving the software.

**Comment by EricdeWaal** [comment]
OK, I will not combine issues anymore.
You marked this report as Invalid. Do I understand from your comment that both issues have already been solved but not yet implemented in version 1.0.3?

**Comment by EricdeWaal** [comment]
The error probably got into the log when I was installing, if I look at the time.
