### ISSUE TITLE
There is no first-run  install with a simple nginx conf

### ISSUE THREAD

**Issue by nobicycle** [akeeba/panopticon#278]
## Describe the bug

There is no first-run  install with simple a nginx conf. The login page is displayed instead.

![panopticon localdomain e807cb0e28e3](https://github.com/akeeba/panopticon/assets/1372447/3b3210d4-0cde-45a0-8a24-ffe0973af72d)

## Reproduction instructions

```
server {
	listen panopticon.localdomain:80;
	server_name panopticon.localdomain;
	server_name_in_redirect off;
	root /srv/http/panopticon;
	client_max_body_size 20M;
	index index.php index.phtml index.html;
		location / {
				try_files $uri $uri/ /index.php?$args;
		}
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+?\.php)(/.*)$;
		fastcgi_pass legacy;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi.conf;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
```

```
$ php-fpm-legacy -v
PHP 8.1.23 (fpm-fcgi) (built: Sep  1 2023 11:16:38)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies

```

## Expected behaviour
First-run proc.  should appear.

## Environment (please complete the following information)
 - Panopticon version: 1.0.2
```
$ php-fpm-legacy -v
PHP 8.1.23 (fpm-fcgi) (built: Sep  1 2023 11:16:38)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies

```

 - Database type MariaDB
 - Database version: 11.1.2-MariaDB Arch Linux
 - Browser [e.g. Chrome, Safari] Vivaldi
 - Browser version [e.g. 22] 6.4.3160.34

**Comment by nikosdion** [comment]
This issue has been marked as a duplicate. It is something which has already been reported and fixed in 1.0.3.

Before submitting an issue we kindly ask you to check all issues, open and closed. We understand it will take you a few minutes longer, but it will save us the limited amount of developer time we have available to improve this software.

Thank you for helping us help you!

**Comment by nobicycle** [comment]
Apologies but every key word "first-run", "install", "nginx" yielded nothing across open+closed issues.

**Comment by nikosdion** [comment]
It has nothing to do with NginX. That's the keyword that threw you off.
