### ISSUE TITLE
scss compile

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#281]
Spotted a few contrast issues that should be easy to fix in the scss but I must be missing something as I dont see how you are generating the theme.min.css

**Comment by nikosdion** [comment]
When you run `composer install` it triggers the `npm-deps` part of the `composer.json` file. That calls `\Akeeba\Panopticon\Composer\InstallationScript::sass` which basically runs `sass media/scss/theme.scss:media/css/theme.min.css -s compressed --update`.

**Comment by brianteeman** [comment]
That is what I expected BUT if you delete the contents of media/css and the run `composer install` only the fontawesome files are generated

**Comment by nikosdion** [comment]
And fixed. You can now also run `composer run-script scss` to regenerate the SCSS files much faster than going through the whole `composer install` process.

**Comment by brianteeman** [comment]
Code updated but still has issues :(


composer run-script scss 

```
> \Akeeba\Panopticon\Composer\InstallationScript::sass
'sass' is not recognized as an internal or external command,
operable program or batch file.
```

composer install
```
> \Akeeba\Panopticon\Composer\InstallationScript::copyNodeDependencies
> \Akeeba\Panopticon\Composer\InstallationScript::babel
> \Akeeba\Panopticon\Composer\InstallationScript::sass
'sass' is not recognized as an internal or external command,
operable program or batch file.
> \Akeeba\Panopticon\Composer\InstallationScript::copyPackageLock
> \Akeeba\Panopticon\Composer\InstallationScript::makeVersionPhp
> \Akeeba\Panopticon\Composer\InstallationScript::postComposerUpdate
> \Akeeba\Panopticon\Composer\InstallationScript::schemaUpdate
```
