### ISSUE TITLE
Extension, new version. No Mail - no template

### ISSUE THREAD

**Issue by Rolli1962** [akeeba/panopticon#283]
System configured only to send mail by new version of an extension.

Have running 1-0-4-dev202311081912  (thanks), so I am sure that mails working in general.

Set log level to "info". Found out, that panopticon try to send a mail (log entry in sendmail.log). And that there do no template exist for this situation.
Created an template - with this it is working.

Maybe the template is missing only in the dev-version.

## Reproduction instructions

Step by step instructions to reproduce the behaviour:

## Environment (please complete the following information)
 - Panopticon version:
 - PHP version:
 - Database type [e.g. MySQL, MariaDB]:
 - Database version:
 - Browser [e.g. Chrome, Safari]
 - Browser version [e.g. 22]

**Comment by nikosdion** [comment]
This is indeed a bug in the post-upgrade code. I have fixed that now, so the next update will install the missing mail templates.
