### ISSUE TITLE
Edit Avatar - proposal

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#287]
## Describe the bug
when the user does not have a gravatar then a default mystery person image is displayed because we are adding `d=mp` and that works great.

The problem is that the edit link doesnt check to see if it is a valid gravatar before displaying the link.

There is some code to check if the link is empty but unless a user was somehow able to create an account without an email address it will never be empty.

This is resulting in a link **Edit Avatar** which produces a 404 and users are reporting this as an error in panopticon. We should be checking if the email address is valid on gravatar and then if it is **not** valid either
1. dont display the link
2. change the link to the gravatar home page

![image](https://github.com/akeeba/panopticon/assets/1296369/97a061fd-40d1-4246-baff-b15ed8c881db)

**Comment by nikosdion** [comment]
You are asking for something Gravatar does not implement for obvious reasons. Think, Brian. If the “username” is the hash of the email and there is an API where I can check if a hash is registered what does that mean in terms of, say, credentials stuffing attacks?

**Comment by nikosdion** [comment]
Again, the way that works is by adding a parameter to the Gravatar URL which points to the URL of a locally generated image. Wouldn't you know it, that local URL can be something like `https://www.example.com/avatars.php?mode=letters&initials=BT`.

Does that mean that when I am constructing the Gravatar URL I know if that email address exists in Gravatar or if it's going to use my alt image? Of course not.

Look. If you are all so fucking stupid as to not understand that Gravatar is a **THIRD PARTY SERVICE** and I have no control over it I will waste my Saturday morning to put that feature behind a new option called "I am not so fucking stupid as to not understand Gravatar is a third party service". Jesus wept! Common sense is not common at all!!!

**Comment by nikosdion** [comment]
There you go. Mystery person icon everywhere.

If anyone wants to re-enable avatars, well, they can. But not in the options presented in the user interface. They have to edit the config file manually. In this case, they should also be able to provide user code to handle the `onUserAvatar` and `onUserAvatarEditURL` events to implement whatever library they want to implement, including the mythical library that you think can tell if a Gravatar is available or not. I would actually show you the doc pages which say this is not possible with the _current_ Gravatar API (they are going to launch a new one, sometime in the future), but Automattic managed to screw their site up and they return 404 at the moment.
