### ISSUE TITLE
Scheduled Available Update Summary Emails

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#301]
Instead of sending one email per update found we can try to give the alternative of _summary_ emails. One email per site.

Scheduled update summaries are, in fact, _tasks_. Remember that each task already has a frequency and the site it concerns. Further to that, we need the following parameters:

* `core_updates`: boolean, default yes. Include pending core updates.
* `extension_updates`: boolean, default yes. Include pending extension updates.
* `prevent_duplicate`: boolean, default yes. See below.
* `updates_identifier`: string, used with `prevent_duplicate`, see below.

The recipients of the email, and the email languages, are determined the same way as the individual update emails.

The `prevent_duplicate` allows us to prevent sending the exact same email every time we run this task if nothing has changed with regards to how many and which updates are available. To do that, we need to somehow know which updates we included in the previous email. This is where the `updates_identifier` comes into play. It is a SHA-1 sum of the JSON representation of the following array:
- core: NULL if not reported, simple array of current version and new version otherwise.
- extensions: NULL if not reported. Array of extension ID → current version, update version, sorted by extension ID ascending, including only extensions with updates.

If the current SHA-1 sum is identical to the `updates_identifier` we don't send an email. Otherwise, we update the `updates_identifier` and send an email.

If someone wants to use summaries _instead of_ individual emails, they need to set the action for the core and extension updates to None instead of Email. This way, detecting an update won't trigger an email. Only the scheduled summary will trigger an email.

Each site will have a button to manage these Scheduled Available Update Summary Emails. The default setup for adding a new item is to send it on midnight every Monday (weekly email), with both `core_updates` and `extension_updates` enabled.

## Why not have multiple sites per email

If you were to have multiple sites reported in a single email you would not be able to send the email to all users who can view _any_ of these sites. If Alice can view Site A, Bob can view Site B, Charlie can see all of them, Site A CC's Daniel and Eve, Site B CC's Daniel and Frank, who do you email when you have selected sites A and B? You can email Alice, Bob, Charlie, Daniel, Even and Frank. Clearly, Alice and Eve should not be notified about Site B, whereas Bob and Frank should not be notified about Site A. If you exclude them and just send an email to Charlie and Daniel you're doing something wrong, because the other four people are not notified about their sites. Therefore you'd need to send a **different email to each person**. This becomes incredibly complicated when you have dozens of sites.

Even worse is selecting a language for the emails. What if Alice wants her emails in English, Bob wants his emails in French, and Charlie wants his emails in German? Before you know it, we end having to create a different email per recipient which is a major headache. Yes, we can programmatically figure this out **but good luck to the poor sod who will try to understand who will receive what email about which sites and which languages**.

My experience is that this level of complexity is far beyond the cognitive abilities of 75% of users, leading to at least three quarters of users being unhappy because their (false, unwarranted, and illogical) expectations are not met by the cold, hard reality of what they've configured. So, eff that.

Instead, we can have one email **PER SITE**. The only thing that changes per user is the **LANGUAGE** of the email whose source is fairly obvious to the vast majority of users.

So, yes, we kinda have to limit the possibilities of this feature to make sure the vast majority of users "gets it". It is one of the many trade-offs one has to consider when writing mass-distributed software.

**Comment by Rolli1962** [comment]
Sounds good. Especially it is up to the administrator of panopticon to activate it or not.

My understanding is, that it is possible to have a kind of main-administrator for panopticon and all the sites and ... I name it sub-administrator for dedicated sites or group of sites.
Could it make sense that it would be possible to create more than one summary-profile? Than it would be possible to configure the relevant mail-addresses in each profile.

**Comment by nikosdion** [comment]
@Rolli1962 Yes, you will be able to create as many as you want. That's why I am saying you will be creating scheduled summary entries and not entering scheduled summary options in your site :) It is perfectly possible to have the same site appear in multiple summary emails, sent at different frequencies.

@brianteeman Not quite, because these summary emails only reflect the specific moment in time they are created on. They are a backlog reminder. #303 is the digest you have in mind.

Before you say it, I'll say it. Yes, there is overlap between #303 and #301. In theory, #303 can be configured to create an email with the same information as #301 (disabling everything but the pending updates). I'd like to keep the two features separate because you and I "get it" that #303 is flexible and can do that. I do not expect most people to understand there's overlap, or how to use site action reports to create a backlog reminder email. Also, the wording might be a bit problematic for the recipient. Thus the idea for having two separate features with some overlap.
