### ISSUE TITLE
extention list not alligned with site updates

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#308]
panopticon v1.04
i had 2 sites that has extentions to be updated. the did not get updated because of issues.
i have manualy updated the extentions on the site.
after that, no updates are available.

then i go back to paopticon and reload extention information. Panopticon still reports that the extention needs update.
is this a caching issue or a bug.

1 site is J3 and 1 site is J4.

**Comment by nikosdion** [comment]
The update information is retrieved by Joomla! and conveyed to Panopticon. Panopticon does not check for updates by itself.

When you visit a site's overview page there is a reload button in the Extensions header. Click on it. This asks Joomla! to re-check for updates and return the latest update availability information to Panopticon. Do that and see what happens.

**Comment by johanpeters** [comment]
Hello Nikosdion,
with reload extention list i mean the reload button on the overview page.
i just checked it again and now panopticon is completly up-to-date.. 
so it looks like some delay in information update or something.

i did check on the site on updates.. no updates available.. after that.. i checked panopticon.
based on that i posted this issue.. 

so, now it looks good, all sites are updated complety so i can not perform the same actions.
solved for now. when it happends again i will post it here

**Comment by nikosdion** [comment]
There is always a delay. Remember, Panopticon automatically asks the remote sites for information at most four times an hour.

**Comment by johanpeters** [comment]
okay.. that is probebly the issue.. case closed.. thanks..
