### ISSUE TITLE
Overview Core Update shows all sites

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#331]
Overview - Core updates shows all sites configured with current en update version.
in this case all joomla cores are up-to-date so i would expect to have a empty overview.
perhaps a notification regarding joomla 3 and joomla 4 sites that update to 5 should be available.

compair to Overview - Extention updates it shows only the sites with a extention that has a update available
so based on that i should expect Core updates should show the same principle.

**Comment by nikosdion** [comment]
Use the filters.
