### ISSUE TITLE
Dashboard ?

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#334]
I was thinking of submitting a concept pr for a "prettier" dashboard based on some work I have done elsewhere. Just on the off-chance that you have, and if you don't ask then you dont get, do you have a db dump of dummy data I can test the dashboard copncept with. Just saves me a bit of time if you do.

**Comment by nikosdion** [comment]
I don't have any dummy data. So far, I had created sample sites manually. It was more important for me to have sites on many different environments than it was to automate their creation.

**Comment by brianteeman** [comment]
ok - well no harm in me asking
