### ISSUE TITLE
Unable to upgrade from 1.0.4 -> 1.0.5

### ISSUE THREAD

**Issue by jamfx** [akeeba/panopticon#361]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Hi, I tried to update Panopticon and got stuck in a red error.

`Awf\Html\Helper\Basic::date(): Argument #1 ($input) must be of type string, DateTime given, called in /usr/www/users/nikojh/panopticon/tmp/compiled_templates/81cf9333c205e8564bce3257b43931153340b2b3.php on line 57
[View template: ROOT/tmp/compiled_templates/81cf9333c205e8564bce3257b43931153340b2b3.php line 93, compiled from ROOT/ViewTemplates/Selfupdate/default_update.blade.php]`

### Reproduction instructions

1. Log into Panopticon and see update Message
2. Click on "More Information" OR "Administration" -> "Update Panopticon".
3. See errormessage attached.
![error](https://github.com/akeeba/panopticon/assets/4404552/ad095bde-1c75-4634-8d6b-c04b471bf51d)

### Expected behaviour

Update Panopticon as smooth as usual :)

### Actual behaviour

Throwing error.

### Screenshots

See Screenshot attached in upper part.

### Panopticon version

1.0.4

### PHP version

8.2.13

### Database type

MySQL

### Database version

8.2.13

### Browser

Other Chromium

### Browser version

119.0.6045.159

**Comment by nikosdion** [comment]
Delete the folder `tmp/compiled_templates`. Did that help?

**Comment by jamfx** [comment]
Ok, update went through after deleting the folder. But a lot of language-Strings (german) where missing. I switched back to english.
Worked. Case can be closed.
