### ISSUE TITLE
Akeeba Backup Pro integration not working

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#372]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

i have Akeeba Backup and Akeeba Tools, both Pro versions.
Akeeba Tools is connected now. Akeeba Backup link is broken status. i can not get it connected.
its a J3 website btw.

### Panopticon version

1.0.5

### PHP version

8.1.2

### Database type

MySQL

### Database version

8.1

### Browser

Chrome

### Browser version

latest

**Comment by nikosdion** [comment]
Do you get any specific error message?

**Comment by johanpeters** [comment]
> Do you get any specific error message?

not specific. just the message that  Akeeba Backup is not linked.

**Comment by nikosdion** [comment]
@Raxiel1987 You seem to have a different issue. You have entered the URL for Akeeba Backup's API endpoint instead of your site's URL in the Site URL box.

**Comment by nikosdion** [comment]
> mh no.. 1 month ago where working good and nothing changed..
> i host website on my server in my office and a month ago i've changed isp company and i've trouble configuring they're modem.

I think you've got the smoking gun right there.
