### ISSUE TITLE
SMTP Authentication radio button is deactivated automatically after page refresh

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#390]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

The "SMTP Authentication" radio button in the Email section deactivates automatically after a page refresh, therefore also after a save.

Not having noticed it immediately, I really wasted a lot of time (even checking the SMTP parameters of the mail server) to understand what was wrong (remembering that I had activated SMTP authentication).

### Reproduction instructions

"Save" or "Save and Close" the email page

### Expected behaviour

-

### Actual behaviour

-

### Panopticon version

1.0.5

### PHP version

8.2

### Database type

MariaDB

### Database version

10.11

### Browser

None

**Comment by nikosdion** [comment]
This should be like the example of what a great bug report looks like! Short, to the point, reproducible, therefore easily fixed even while I'm on vacation 😆 

Thank you!
