### ISSUE TITLE
500 error on connection after updating to J5!

### ISSUE THREAD

**Issue by wderuijter** [akeeba/panopticon#400]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

After updating a site to J5! I saw an error upon refresh of the site in panopticon. 
Tried these steps:
- I've reset the API key on the site
- I've emtied the panopticon /tmp folder
- I've reinstalled panopticon
- I've created a new Admin Tools .htaccess file

The error states: 
Process step: Unauthenticated access (can I even access the API at all?)

HTTP Status	500
HTTP Body	
Call to a member function addRoutes() on null

1; mode=block
X-Content-Type-Options
nosniff
nosniff
Content-Security-Policy
frame-ancestors 'self'
x-frame-options
SAMEORIGIN
referrer-policy
unsafe-url
cross-origin-opener-policy
same-origin
strict-transport-security
max-age=31536000
Expires
Wed, 17 Aug 2005 00:00:00 GMT
Cache-Control
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
no-transform
Pragma
no-cache
Upgrade
h2c
Connection
Upgrade, close
Last-Modified
Tue, 19 Dec 2023 19:19:57 GMT
Transfer-Encoding
chunked
Content-Type
text/html; charset=utf-8

### Reproduction instructions

I can't reproduce it on another site. This is the only one with the problem.

### Expected behaviour

Being able to add a site to panopticon.

### Actual behaviour

Gives me the 500 error.

### Panopticon version

1.0.7

### PHP version

8.2.13

### Database type

MariaDB

### Database version

10.6.15

### Browser

None

**Comment by nikosdion** [comment]
> Call to a member function addRoutes() on null

This means that a plugin on your site is causing a problem. That's why it's only on one site, and not on any other site.

**Comment by wderuijter** [comment]
@nikosdion just to let you know, this is what seems to have fixed it although I have no idea why. I've disabled the FOF, FOF3 and FOF4 framework extensions and reinstalled Admin Tools and Akeeba backup. After that the connection could be made.

**Comment by nikosdion** [comment]
FOF and FEF are End of Life since the release of Joomla! 4.1, two years ago.

**Comment by wderuijter** [comment]
Yeah, it was an older site from 2020 I upgraded to J5.

**Comment by nikosdion** [comment]
@wderuijter You can definitely remove FEF and FOF now.

**Comment by wderuijter** [comment]
Done, thanks @nikosdion
