### ISSUE TITLE
webkey authentication error after login

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#406]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

i have MFA and webkey enabled.
when i use MFA i get logged in 
when i use webkey a error after confirmation

### Reproduction instructions

1. login username and password
2. accept webkey challenge on phone
3. display error

### Expected behaviour

i expect to get loggedin 

### Actual behaviour

display error

### Screenshots

sent by mail

### Panopticon version

1.0.7

### PHP version

8.1.2

### Database type

MySQL

### Database version

unkown 

### Browser

Chrome

### Browser version

latest

**Comment by nikosdion** [comment]
Your browser returned invalid data. However, I cannot reproduce this issue using Chrome 120.0.6099.109.

The best I can do is make a small change to simply swallow the error and come back to you with a generic error that WebAuthn has failed.

**Comment by johanpeters** [comment]
okay..
reconnect / reconfigure webkey to see if this solves the problem?
i use webkey also on sites on same system, browser, phone.. no issues..

**Comment by nikosdion** [comment]
Yes, please. Something seems to have gone wonky.

FWIW I am testing with macOS using both built-in WebAuthn (FaceID) and a YubiKey 5C, and a Linux box using a YubiKey Nano.

**Comment by johanpeters** [comment]
i tried it, but same issue.

**Comment by nikosdion** [comment]
Can you try using a different browser?

**Comment by johanpeters** [comment]
Hello Nicholas,
tried Safari.. and it works.. grr
so it looks like a google chrome issue. i have the latest version.

**Comment by nikosdion** [comment]
This is so weird. I tried this combination and it works.

Start disabling extensions on Chrome. I am pretty sure one of them is doing something funky.

**Comment by johanpeters** [comment]
i already tried incognito and cleared cache..
same issue.. i will try a other system.. perhaps something specific on this
system (Macbook Air).

i keep you posted.

**Comment by johanpeters** [comment]
Hello,

I tested it on a other pc.. same issue.
Tested on chrome mobile.. it works.

I don't understand it.. 

⁣Met vriendelijke groet
Johan Peters
​

Op 20 dec 2023 10:26, om 10:26, Johan Peters ***@***.***> schreef:
>i already tried incognito and cleared cache..
>same issue.. i will try a other system.. perhaps something specific on
>this
>system (Macbook Air).
>
>i keep you posted.
>
>
>On Wed, 20 Dec 2023 at 10:24, Nicholas K. Dionysopoulos <

**Comment by johanpeters** [comment]
Hello Nicholas,
i have downloaded ms Edge for Mac.
i get the same error.

**Comment by nikosdion** [comment]
Do you use a hardware token? If so, what kind of make and model?

**Comment by johanpeters** [comment]
Hi,

No, i use a google pixel 7a mobile phone

⁣Met vriendelijke groet
Johan Peters
​

Op 20 dec 2023 20:00, om 20:00, "Nicholas K. Dionysopoulos" ***@***.***> schreef:

**Comment by nikosdion** [comment]
You are trying to use PassKeys, yeah? This is still not working very reliably on macOS unless you have a Mac and an iPhone. Add one more WebAuthn entry using the biometrics of your Mac to create a new PassKey. You can then use it across all browsers on your Mac.

**Comment by johanpeters** [comment]
Hello,

Yes indeed.. i tried MacOS and windows..
Same issue..(first time registered on mac)
I will try setting things up on windows to see if thats solves it.


⁣Met vriendelijke groet
Johan Peters
​

Op 20 dec 2023 20:19, om 20:19, "Nicholas K. Dionysopoulos" ***@***.***> schreef:

**Comment by johanpeters** [comment]
Goodmorning Nicholas,
i tried several things this morning.. starting from a windows PC.
i removed the passkey.. and set it up on a windows PC with Edge, it works
i test it on chrome on windows pc, error
i test it on mac with saffari, it works
i test it on mac with chrome, it fails
i test it on windows with brave, it fails
i test it on mac with brave, it fails

so, or there is something wrong on my panopticon setup or its a bug for
some reason.
al the errors are the same line and same error.

only thing i want to test to create a other user account on panopticon and
see of it works with that account.

if its helps to debug.. i can arrange access for you

**Comment by nikosdion** [comment]
Does your setup work with Joomla? I am asking since we're using the same code.

Access would NOT help me, since I have already confirmed that my own authenticators work fine across devices in select combinations.

Please **DO REMEMBER** that PassKeys **ARE NOT YET** fully functional. Not in Panopticon, _as a whole_. It's a very new technology with all sorts of weird issues still occurring. Not to mention, if you're on Linux you're screwed; there is no such thing as PassKeys shared across devices…

Yes, I've had weird behaviour with them, too. I can't use my PassKeys on my iPad, even though they work fine on macOS and iPhone and I have confirmed the Keychain syncs across all three devices. I cannot use a Samsung Android device with any desktop OS, only with Android device itself; others had success with other Android devices. Chrome on macOS can authenticate with PassKeys created by Safari, but doing it the other way around does not work. And that was with Joomla and Panopticon. Using other WebAuthn implementations I get even worse support for PassKeys.

I can't waste any more time on that since there is nothing more I can realistically do.

My solution is simple.

Create a PassKey for each device and browser you are going to be using. How do you log into a new device to do that? Either set up a TOTP (authenticator code), or use the emergency codes. Or use a hardware FIDO2 (WebAuthn) dongle and adapters to connect it to each device. I've used all three methods.

**Comment by johanpeters** [comment]
Hello Nicholas,
yes, on joomla (same shared hosting server and account) webkey works.
for now, i am back to TOTP.. so no problem..

many thanks for your time.. and keep focus on the project is more
important than this issue.

with regards

**Comment by nikosdion** [comment]
Hm, if Joomla works but Panopticon doesn't something's up. I will try to make a reliable reproduction of the working condition with Android so I can test some more. I am wondering if the ugly hack I had done in Joomla to support Android because we were using an old version of the WebAuthn library is still necessary, despite the library adding support for it in this newer version I am using in Panopticon…

**Comment by nikosdion** [comment]
I have good news and bad news.

The good news is that I was able to use my Android phone (Samsung A13) with WebAuthn.io, Joomla 5, and Panopticon 1.0.7 with my Mac (macOS Sonoma 14.2.1) using both Safari and Chrome. For Panopticon in particular I registered the Passkey using Chrome and was able to use it with both Chrome and Safari – and Iron, another Chromium-based browser. Critical detail: Bluetooth had to be enabled on both my Android phone _and_ my Mac.

The bad news is that I was able to use my Android phone with Panopticon. This means that it's not a problem with Panopticon but something truly strange going on with your environment. Sorry ☹️

**Comment by johanpeters** [comment]
Strange.

Let me check webauth.io also .. 

Keep you posted..

I run panoption from 1.00 intil 1.0.7..
Perhaps a clean install to test?

⁣Met vriendelijke groet
Johan Peters
​

Op 21 dec 2023 15:05, om 15:05, "Nicholas K. Dionysopoulos" ***@***.***> schreef:

**Comment by nikosdion** [comment]
My _newest_ install started as 1.0.0, updated with each version to 1.0.7.

My _oldest_ install started as the original, pre-alpha release.

It's not a matter of a clean versus new install. Or at least it wouldn't make sense.

If you want to be 100% sure, delete the `vendor` folder and re-upload it from the 1.0.7's package. Just in the unlikely event that this didn't happen during update and there's any file stuck in there that somehow causes a problem I can't otherwise reproduce. I've seen weirder things!

**Comment by johanpeters** [comment]
Hello,

i just tried it.. same result.. so reload vendor folder did not fix
anything.

**Comment by nikosdion** [comment]
So, definitely not a code issue, and not reproducible anywhere else.

The only thing that's left is for me to use my known good environment to try creating a PassKey on your server. To do that, I need the following connection information to your Panopticon site.

**Site connection information**

* Your installation's URL e.g. `https://monitoring.example.com`
* Super User username
* Super User password

(Best create a new Super User for me)

**(S)FTP connection information**

* Hostname
* Port (if other than 21 or 22)
* Username
* Password

Do **NOT** paste this information unencrypted. GitHub issues and discussions are publicly visible. Instead, follow the instructions below to send me an encrypted copy of the information which can only be decrypted by me:

* Go to https://keybase.io/encrypt
* In the **Recipient** field type `nikosdion`.
* It will show you my face, my name, and the fact that I have linked my same-named GitHub account; verify this information and click on my face.
* In the **Message to encrypt** area enter the information I asked you above.
* Click the Encrypt button.
* After a short while the text area changes its title to **The secret message**.
* Click in the text area to copy the secret (encrypted) message.
* Paste it to your next reply to me.

This is perfectly safe to do! It uses public key encryption, just like HTTPS, with a _much, MUCH stronger cipher_ (3744-bit Elliptic Curve Cryptography which is insanely secure). The message can only be decrypted with my secret key which is safely stored on a hardware token, protected by a PIN.

Please make sure that you test the access credentials using a separate browser / (S)FTP software than what you normally use to ensure that they really work. Please make sure that there are no geographic or other restrictions which may prevent me from accessing your site. Kindly note that I am on the [Asia/Nicosia timezone](https://www.timeanddate.com/worldclock/cyprus/nicosia) and I am handling support free of charge; some delays are to be expected.

**Comment by johanpeters** [comment]
Hello Nicholas,
as requiested and tested

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

wcBMA6+1LLjxrhABAQf/W1o9LkddkmF92jUH8E1embkGJLsNXMxQ+KIYRF+U3SVL
DRaS8mC/e9bRG8taUo1ShphGAoQ+uGtrI4Dtf02EpDhBQ+Y05ttMa/fpQ3FXOrM7
L+aAtQF6gSTmsjSfbPDc6/HQoANSYQ6Qoe9MTf48JutqsBBlqgWIFq6A0/CG8/4H
ZDqZgm+5O37DzFQZV3Dv411tCqVvWay4ptr9kXbVZRnF9EtOspQFkUdJFIJIdFJu
L6WhBcAI8Zy7mwFcuQu6jDzZC2jIEfaH8VEIMoQh6otuiCqzsrVS42Jur8eH+NZS
tfK4JmpqS5WepGvbOpGK65q5K2DlWOOegfApd0zTd9KXATZYhdN8uNjcaRfgw0mk
FqeSPjvDTOezI5mmM5aye7CqfrMZYqiece09rimAzWSg+49Ts5c+v4kUsE7hIWOb
B5m+/eep98JeS3kJtNL2LhwFf985C4rwdSxVA0FCbAdVvpY4MwvhD6SWZa+DmrCB
e4Zu7/355C7dj3lRUDkId9PybCA9J/ZZV+roUT4f8qsKmzYoJIQ40A==
=Lwlx
-----END PGP MESSAGE-----

**Comment by nikosdion** [comment]
Thank you! I can confirm that I had fixed this with the "blind" fix  db8cf99be3cda56ed574d8ae137794bc93ee2a8f and now I understand why that fix worked.

Chrome returns an empty user handle during the WebAuthn "login" when using an Android device as the authenticator (it does not happen with macOS passkeys). Passing that null (empty) value to Base64::decode() causes an error. However, the user handle is ignored anyway as we only ever match the certificate which is impossible to forge, not the user handle (which we look up in the database anyway).

I made the small change to your site so you can authenticate without a problem. The fix will make it to version 1.1.0 scheduled for after the holiday period.

**Comment by johanpeters** [comment]
Hello Nicholas,
thats create news and already tested it.. works like a charme..
great work and support.
many thanks ..

**Comment by nikosdion** [comment]
You're welcome!
