### ISSUE TITLE
petit-vue

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#408]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

dashboard is empty

### Reproduction instructions

current git repo
swtich from Sites Overview– Table to Dashboard

### Expected behaviour

dashboard view of sites

### Actual behaviour

dashboard empty of sites

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/1296369/eb91e016-a01b-4eba-b2e1-26ba5448f59f)

### Panopticon version

1.0.7

### PHP version

8.1.3

### Database type

MySQL

### Database version

8

### Browser

None

### Additional information

petit-vue error

![image](https://github.com/akeeba/panopticon/assets/1296369/258d3d88-4a51-4c48-8249-eedf414a3c00)

**Comment by nikosdion** [comment]
Do you have the file media/petite-vue/petite-vue.min.js? If you do, which browser are you using?

**Comment by brianteeman** [comment]
yes i do

![image](https://github.com/akeeba/panopticon/assets/1296369/b9cba1b0-8aae-4d7e-9943-d54b0347d7ec)

tested on chrome windows and safari on sonoma

**Comment by nikosdion** [comment]
If you try to access this file directly from a browser, does it display?

FWIW I also just used Safari and Chrome on macOS Sonoma. I can see it just fine. This rules out the possibility of a browser incompatibility. We have already ruled out a missing file. The only thing left is a browser issue.

Speaking of which, if you have a .htaccess file try removing it. If that works, please take a look at the htaccess.txt file; I have updated the CSP to account for Petite Vue's use of eval().

**Comment by brianteeman** [comment]
1. yes I can access it directly
2. my sonoma test was using browserstack so cant be a browser plugin
3. i had no root .htaccess

**Comment by nikosdion** [comment]
I don't know, then. I can see the Dashboard just fine. You have a message claiming that the browser cannot find the JS file which exists, and your server does not block it. I do not know of any other reason the browser would claim the file does not exist.

**Comment by brianteeman** [comment]
testing on another server

**Comment by brianteeman** [comment]
Completely new server
git clone
composer install
panopticon install
skip cron setup
switch to dashboard view
same error as before

**Comment by nikosdion** [comment]
Can you please verify that the new server does have the petite-vue.min.js file?

**Comment by brianteeman** [comment]
of course I verified that first https://panopticon.brianstest.site/panopticon/media/petite-vue/petite-vue.min.js

**Comment by brianteeman** [comment]
found the problem - or at least why it works for you and not me

I bet you have debug on?

If I turn debug on then it works for me now - but still not if debug is off

Further check shows that the problem is only when using the minified version of main-dashboard.js

**Comment by brianteeman** [comment]
Confirming that the problem is with the minification

`
import {createApp} from "../petite-vue/petite-vue.min.js";
`

is changed to
`
var _petiteVueMin=require("../petite-vue/petite-vue.min.js")
`

![image](https://github.com/akeeba/panopticon/assets/1296369/7a0ae397-2794-44f3-8347-cfc80054f29c)

**Comment by brianteeman** [comment]
Confirming that this worked.

**Comment by nikosdion** [comment]
Thank you!
