### ISSUE TITLE
tinymce permanent dark mode

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#410]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

when in dark mode tinymce ui and content is in dark mode
when in light mode the ui is in light mode but the content still in dark mode

### Reproduction instructions

tested with the site notes editor

### Expected behaviour

full light mode

### Actual behaviour

content still in dark mode

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/1296369/05809caa-8bfe-4ca2-a8b1-0bc5dd4d0a78)

![image](https://github.com/akeeba/panopticon/assets/1296369/d2fc912a-1f01-4276-82b7-7a71a858d869)

### Panopticon version

git

### PHP version

8.2

### Database type

MySQL

### Database version

8

### Browser

Chrome

**Comment by nikosdion** [comment]
Thanks! There was a small typo in the JS.

**Comment by brianteeman** [comment]
confirmed as fixed
