### ISSUE TITLE
Automations

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#413]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

at a minimum there should be a notice/warning displayed on the view=scannertasks and view=backuptasks

### Reproduction instructions

for a site which does not have AB or AT set up an automation

### Expected behaviour

info that it is not possible for the automation to run on the site as AB/AT are not installed etc

### Actual behaviour

no message

### Panopticon version

git

### PHP version

8.2

### Database type

MySQL

### Database version

8

### Browser

None

### Additional information

I thought we could use the same code as used here

https://github.com/akeeba/panopticon/blob/354229998f216a5144ec2bd221f9ab02cfdb8d83/ViewTemplates/Sites/item_admintools.blade.php#L91-L102

But I tried and failed without a lot of code duplication which I'm sure is not right anyway

**Comment by nikosdion** [comment]
Or we could just hide the buttons if the integrations are not set up yet, right?

**Comment by brianteeman** [comment]
I thought about that but maybe you would want to set things up before you install or upgrade the extensions?

**Comment by nikosdion** [comment]
I don't disagree. However, here's the thing. You can't actually set up automations before you have set up the integrations. You can't select a backup profile, for example. So, removing the button before showing the integration makes sense.

After all, the same buttons appear inline on the page _only_ after you set up the integrations.

**Comment by brianteeman** [comment]
You absolutely can set up the php filechange scan automation - I just did it - which made me think you could do it for backup as well. 

So just kill the  buttons
