### ISSUE TITLE
gz on windows

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#422]
Maybe I am misreading the code but...

trying to take a db backup on my windows server and it produces an empty gz file (thats not the problem I am asking)

Looking at the code in dbutils/export I can see that various tests are run and that debug messages should be logged.

I have set the log level in the system config to debug so I would expect that the debug messages would now be output I go to administration log files but there is nothing there.

**Comment by nikosdion** [comment]
Note that by default there is no logger object. It is set through the setLogger method.

When using the CLI, the logger object being set is a ForkedLogger which outputs to the `db_backup` log file and the console.

When using a task, it is sent the task's logger.

When using the web-based task, there's no logger object set.

I believe you refer to the last use case. Let me add a logger.

**Comment by brianteeman** [comment]
> I believe you refer to the last use case. Let me add a logger.

great - thanks - I can investigate further now when I finish my carer duties
