### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#428]
is it intentional or an oversight that there are no tooltips on the new dashboard view. If its the latter just let me know and I can work on that tomorrow

**Comment by nikosdion** [comment]
There are `title` attributes (added a couple of hours prior, you may have not noticed them). Bootstrap tooltips need JavaScript initialisation. This would have to be done every time Petite Vue renders a card. First of all, I am not sure it can do that. Second, even if it can, that's a massive overhead when you are displaying, dunno, 300, 500, 1000 sites. I am afraid that trying to initialise so many JS objects might turn some machines into barbecue grills.

**Comment by nikosdion** [comment]
As I am cleaning my inbox, I realised I forgot to update you on this. I figured out how to have Petite Vue initialise tooltips when the relevant element is created, or its title changed, and how to destroy them when the element goes away using custom directives. So, yep, we now have tooltips, using the native `title` attribute which means that they should be able to be handled by screen readers.
