### ISSUE TITLE
(Sort of) uptime monitoring

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#491]
A lot of people grumble about the lack of uptime monitoring in Panopticon. More specifically, they want to receive an email when a site goes down.

We _can_ do that, with a few caveats.

This needs a task which runs every single minute and tries to fetch a URL on each site, checking its contents for a predefined piece of text.

To make this workable, the uptime task needs to be high priority so it can run regardless of load (e.g. sites being upgraded, extensions updated, backups running, whatever have you). Hence the first problem: if you have more than a small handful of sites you _will_ need additional CRON jobs. This is even more exacerbated by sites which respond slowly, and by having to send emails – both add time to the process. Ideally, you need one extra CRON job for every 30 sites being monitored for uptime. You can possibly scrape by with one extra CRON job for every 100 sites, but you're pushing your luck a bit.

Since Panopticon only ever runs from a single host, it stands to reason that this feature is not really testing whether a site is up, but whether it is accessible from Panopticon's server. This is a fine but important distinction. If your site server is in Frankfurt, your Panopticon server in Amsterdam, and your visitors predominantly in Greece it really means zilch whether Amsterdam can talk to Frankfurt or not, since that's NOT where your audience is. And yes, a site can be up for some regions and inaccessible from others (there's such a thing as network issues, believe it or not!). So, yes, a site might appear up but you will be perceiving it as down, or vice versa.

## Implementation

There is a global kill-switch option: `uptime`. By default enabled. When disabled the scheduled task for uptime monitoring will return without monitoring anything.

Each site will have the following options:

* `uptime.enable` Default enabled.
* `uptime.path` The URL path to access for uptime monitoring. Default: `/`
* `uptime.string` Default: empty. The string which must be present in the output to consider the site up. The page contents are stripped of tags and all whitespace is collapsed to single space characters when performing this check: this allows `Foo Bar Baz` to match more complex HTML like `<h3>Foo <span class="icon-whatever"></span>Bar<span class="float-right">Baz</span>`. If it's empty, we assume that ANY response in the 2xx range means the site is up.

For the sake of simplicity, there are some hardcoded decisions:

* There's a hard timeout of 15 seconds. If your site won't load within that amount of time it's perceived to be down by your visitors anyway.
* Redirections are followed. Just because I can guarantee that it will be necessary for multilingual sites.
* You only get one URL to test for each site being monitored.
* When a site is down, the timestamp of the event is recorded in the site config option `uptime.downtime_start` as a UNIX timestamp.
* The site down and site up events are recorded in the actions log.
* Emails are sent on site up and site down.
* When the site goes back up the total amount of downtime is recorded in the event, and sent with the email using the variables `[DOWNTIME_HUMAN]` and `[DOWNTIME_SECONDS]`.
* We **DO NOT** record historic information of downtime over any period of time.

For the presentation of the uptime status we will use an event: `onSiteGetUptimeStatus(Site $site)`. We will have a default plugin class to handle this event _if_ the global `uptime` flag is enabled. Otherwise, it can gracefully let a different plugin class respond – which allows custom integrations with third party services.

While this is possible and we'll integrate it, it's NOT a good idea. It's best to use [a third party service](https://github.com/akeeba/panopticon/wiki/Uptime-Monitoring#why-not-integrate-with-a-third-party-service). Even in their free tiers they will send you emails when a site is down, they have multiple geographic locations, and they keep historic data. But, hey, if you want to torture yourself with a solution that can't be anywhere near that good, no problem!

**Comment by brianteeman** [comment]
Instead of all of this work (with its noted limitations) why not just use https://github.com/louislam/uptime-kuma

**Comment by nikosdion** [comment]
@brianteeman This falls under the category "why not just use a third party tool". This is not something that can be a part of Panopticon. It is its own, self-hosted Node.js application. Remember, I have already documented that using a third party tool is the best course of action.

If you look at what you pointed me to, you will see that in order to address the first bunch of problems (concurrence and overall load) it uses a Node.js server. Node.js is an excellent choice for this task since it supports asynchronous programming, something that PHP really doesn't – yes, I am aware of Fibers, but they do not solve this problem here.

Even so, the second problem (monitoring is meaningless when done from a single location) is not addressed. Addressing that requires an even more complex setup. Not hugely complex, a single person can manage it, _as long as they know about DevOps_. That's, of course, incompatible with our audience.

Even if setting up multiple monitoring locations was easy, it would be expensive. You'd need to be spending between $7 and $20 per location per month. Let's say $15. At a minimum of four monitoring locations to make practical sense that's $60 per month, or $720 per year. Again, outside the means of our target audience. In fact, for just under $500 a year you could get HetrixTools for 200 sites and 12 monitoring locations. Beyond that, they would give you a volume discount, therefore your break-even point would be in the thousands of sites.

To recap, self-hosted uptime monitoring makes sense EITHER if you want to monitor up to a couple of dozens of sites and you're okay with the results not being very accurate (and possibly not keeping uptime history), OR if you are monitoring dozens of thousands of sites. Everything in between is best served by a third party service.

The problem I am trying to solve here is NOT a practical one. I have already documented that the _practical_ solution is using a third party service for pretty much the entire target audience of Panopticon (including people with a handful of sites, as Panopticon will not offer an uptime history, or a breakdown of the response time between SSL handshake, waiting time, and response download time).

The problem I am solving here is a human one, namely _recalcitrance_. There are people who flat out refuse to use Panopticon unless it has uptime monitoring, even if it's a token one, which will kinda-sorta send them an email around the time their site goes down. This is what I am solving, and it will of course have a global kill-switch because most people with more than a small handful of sites will quickly realise that my recommendation to use a third party service for uptime monitoring is the right approach.

**Comment by brianteeman** [comment]
It was a comment to other readers that they should look at uptime-kuma for their uptime monitoring needs.

**Comment by nikosdion** [comment]
@Raxiel1987 Just adjacent words on a page.

Here's an example. In [our site](https://www.akeeba.com) you will see there's a box for Akeeba Backup for Joomla!. The actual HTML is:

```html
<span class="frontpage-product-title">akeeba backup <span>for Joomla!</span></span>
```

What you would enter in Panopticon is `akeeba backup for Joomla!`. All the enclosing HTML is removed when checking for a string.

Regarding Uptime Kuma and others: I am designing the feature in such a way that it's possible to create “plugins” which allow you to integrate with whatever service you want. 

It makes no sense providing public pages for the subpar uptime monitor in Panopticon – I know it cannot really be made much more than that without having to ask you to use software commonly unavailable on commodity hosting (Redis at the very least, Node.js or Dart, set up daemons, …).

As I said, I _know_ how to build an uptime monitor service. I also know that it makes no sense asking most of you to run it. Very few will be able to, and those who do would probably balk at the cost. It makes far more sense integrating with a third party service, but also having a very simplistic built-in option for those users who only have a small handful of sites and nothing more.
