### ISSUE TITLE
email not receiving when core or plugin update installs

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#493]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

i have a problem, or may i have not understood the guides
i configured smtp mail for sending email and it works when sending test mails.
i configured the email templates when updates for core and plugins are installed that i will receive email.
now what other i have to setup?
i've checked in every website configure under automation/schedule update summary and configurared like screeenshot
![chedule update summary](https://github.com/akeeba/panopticon/assets/98883346/baf0e3b4-08ae-4767-9777-0943097a21c1)

is this correct? or the email will arrive at certain hours?

### Panopticon version

1.0.7

### PHP version

8.2.13

### Database type

MySQL

### Database version

8.0.34

### Browser

None

**Comment by nikosdion** [comment]
There is a bug in the currently released version. You need to have a non-empty CC email address for an email to be sent to the other recipients.

**Comment by nikosdion** [comment]
Yep, the rest of the configuration is correct.
