### ISSUE TITLE
Automation menu

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#501]
The strings in the automation menu are not consistent (schedule/scheduled)

![image](https://github.com/akeeba/panopticon/assets/1296369/172cd5d3-4868-4239-bce1-14be324c8b61)

The same strings are also used for some buttons - also not consistent

![image](https://github.com/akeeba/panopticon/assets/1296369/815e9f40-a13f-4f04-a292-c4e821a69fc1)

![image](https://github.com/akeeba/panopticon/assets/1296369/581ae035-7ef1-4298-a934-6ca2426ec06b)

A case could be made for either term
schedule => create an item
scheduled => created items

My personal preference would be that the buttons are "schedule" as in the context of a button they are "performing a task"
This would make all the menu items "scheduled" as in the context of the menu they are listing tasks.

But then we could consider "scheduled" as a redundant word in the menu and remove it

![image](https://github.com/akeeba/panopticon/assets/1296369/05e79f9b-94f8-4d93-ad55-a97c026cb61e)

Should we then be more accurate & descriptive with the "scans" menu item (and make it closer to the page title)

![image](https://github.com/akeeba/panopticon/assets/1296369/3d77169b-bfba-4381-9019-fc294396892c)

### summary
I propose changing the buttons to be "schedule" and create new strings for the menu using the more descriptive option above

**Comment by nikosdion** [comment]
If the buttons are "Schedule" without anything further they would be inaccessible as they are landmarks and announced out of context. Right?

As for the simplified menu item, the labels could be:

* **Scheduled** Update Summary (that's the feature's name)
* Backup
* PHP File **Change Scanner** (that's the feature's name)

I would not oversimplify by converting the drop-down item names into something that's different to what the feature is called. If we're going for consistency, let's go for _consistency_.

**Comment by brianteeman** [comment]
> If the buttons are "Schedule" without anything further they would be inaccessible as they are landmarks and announced out of context. Right?

Sorry for not being clear. I meant change the buttons to 
Schedule Backups
Schedule Scans (change from scheduled)

> I would not oversimplify by converting the drop-down item names into something that's different to what the feature is called. If we're going for consistency, let's go for consistency.

Then Backup should be Backup Tasks ?

**Comment by nikosdion** [comment]
They are all tasks.

**Comment by brianteeman** [comment]
![image](https://github.com/akeeba/panopticon/assets/1296369/ea92dec6-e9f7-4c10-8159-89151fbf6846)

![image](https://github.com/akeeba/panopticon/assets/1296369/5bd7ff36-fa37-49e7-aac0-e953cca0433f)

![image](https://github.com/akeeba/panopticon/assets/1296369/646f4f9c-321c-40db-8a6e-c402d813a62f)

**Comment by nikosdion** [comment]
They are all tasks. The Scheduled Update Summary feature is called Scheduled Update Summary, not Scheduled Update Summary Tasks as the former barely fits when translated in Greek on a 13" laptop screen, the latter definitely does not.

**Comment by brianteeman** [comment]
ok - so to conclude

Buttons changed to be 

- Schedule Backups
- Schedule Scans

Menu changed to be

- Scheduled Update Summary
- Backup
- PHP File Change Scanner

**Comment by nikosdion** [comment]
Yes, correct!
