### ISSUE TITLE
getuptimeoptions

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#503]
Thought I would test this new feature. Is something missing because 
`$results = $this->getContainer()->eventDispatcher->trigger('onGetUptimeProvider');`
always returns an empty array

**Comment by nikosdion** [comment]
Did you enable the feature in System Configuration? It's off by default. On installations with hundreds of sites and only a small handful of CRON jobs having it enabled by default would consume all available CRON job processing time to monitor uptime, without leaving much else for productive work. See https://github.com/akeeba/panopticon/wiki/Uptime-Monitoring#caveats-of-using-the-built-in-uptime-monitoring

**Comment by brianteeman** [comment]
I cant enable it in the system config as the array is empty so you just get "none" in the dropdown (or was there somewhere else)

![image](https://github.com/akeeba/panopticon/assets/1296369/42cb1819-048f-407b-8070-3cb180d4b8c1)

**Comment by brianteeman** [comment]
Confirmed that this is now fixed - thanks

**Comment by morphinestyle** [comment]
Wow! 
But is there an uptime monitor function?
Hadn't it been excluded?

**Comment by brianteeman** [comment]
@morphinestyle not released yet

**Comment by nikosdion** [comment]
@morphinestyle It's a new feature in 1.1.0. But...

**THERE BE DRAGONS!**

It's a very, _very_, **VERY** basic affair which only tells you if a site is up or down, as seen from a single location (your Panopticon server), using rudimentary logic. 

It is far better using a third party service or software with multiple locations, deeper analysis of the response, and retries than the rudimentary feature in Panopticon.

**Comment by morphinestyle** [comment]
I understand, I agree and it's fantastic!
Honestly, it was a feature that I stopped myself from requesting several times by reading what Nicholas wrote...

But I certainly would have proposed it, and I certainly wouldn't have called it "uptime monitor", but regardless of the name: I would have proposed a sort of service that made a constant report, from the single location of the server that hosts Panopticon, to check if the address returns a code 200... A "dead or alive"... A sort of "on/off" that could indicate some problem to my loved Joomla or broken webserver services or the entire server.

A sort of warning light that simply warns you "hey! take a look! maybe something isn't working as it should!"

That's all!
Maybe it could be called something else (out of respect for much more structured uptime monitors) but it will certainly be one of the most appreciated features of all.
And from me too!
