### ISSUE TITLE
SMTP Email configuration does not use Sender Address or Name

### ISSUE THREAD

**Issue by crystalenka** [akeeba/panopticon#513]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

When configuring the email sending, there are fields for "Sender Address" and "Sender Name". However, these do not seem to be used when sending the test email via SMTP

### Reproduction instructions

1. Go to System Configuration.
2. Click on Email. Select "SMTP" as the mail handler.
3. Fill in a different sender email and sender name than the SMTP account info.
4. Save, then click "send test email".

### Expected behaviour

Email received with the sender name and email per the form

### Actual behaviour

Email received with the SMTP email as the sender.

### Panopticon version

1.0.7

### PHP version

8.2.14

### Database type

MySQL

### Database version

8.0.10

### Browser

Safari

**Comment by nikosdion** [comment]
I literally just did that with the current development release and it worked fine. I am closing this since it seems to not (or no longer?) be a problem.
