### ISSUE TITLE
Email only after failed backup when scheduled backups are enabled

### ISSUE THREAD

**Issue by Martin511** [akeeba/panopticon#515]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

I have set scheduled backups.
I get an email after each successful backup for each site.
I can not find a (global) setting to get emails only if the backup failed.

### Panopticon version

1.0.7

### PHP version

8.1

### Database type

MariaDB

### Database version

8.0.10

### Browser

Firefox

**Comment by nikosdion** [comment]
There is no such option in Panopticon.

**Comment by Martin511** [comment]
Thank you for the information.
