### ISSUE TITLE
Missing images in emails

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#519]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

The images in the emails (or in any case the LOGO image) are not loaded, whether with links or inline, because there is a double slash in the URL of the image that should appear in the email

EXAMPLE:
https://my.panopticoninstall.com//media/images/logo_bw.svg

### Reproduction instructions

Send an email

### Expected behaviour

Images visible

### Actual behaviour

Images not visible

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/35969533/a4481343-ee8d-4b48-98b1-842770484449)

### Panopticon version

1.1.0

### PHP version

8.2

### Database type

MariaDB

### Database version

10.3

### Browser

None

**Comment by nikosdion** [comment]
You can change the mail templates. The mail templates are not overwritten when updating Panopticon.

**Comment by morphinestyle** [comment]
Certain! I reported this for Panopticon.

**Comment by nikosdion** [comment]
Thank you!
