### ISSUE TITLE
Back-Button missing under troubleshooting -> tasks / logs

### ISSUE THREAD

**Issue by Engholm** [akeeba/panopticon#530]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

A back button is missing to get back to the previous screen

### Reproduction instructions

1. Go to Troubleshooting -> Tasks or Logs
2. There are buttons for enable / disable / delete
3. Back button is missing

### Expected behaviour

The same back-button as Troubleshooting -> Connection Doctor

### Actual behaviour

-

### Screenshots

<img width="949" alt="pano-back-button" src="https://github.com/akeeba/panopticon/assets/1927499/56e5c949-6da9-44ba-8527-0c757615bb7c">

### Panopticon version

1.1.0

### PHP version

8.2.13

### Database type

MariaDB

### Database version

10.6

### Browser

Firefox

### Browser version

121.0.1 (64-Bit)

**Comment by nikosdion** [comment]
https://github.com/akeeba/panopticon/issues/518
