### ISSUE TITLE
After a change saved on a website, Akeeba Backup becomes "not connected"

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#534]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

If you edit a site and save it, back to the dashboard Akeeba Backup becomes NOT CONNECTED

### Reproduction instructions

- Edit any site that uses akeeba backup
- Save
- Return to the Dashboard

### Expected behaviour

Akeeba Backup still shows "fresh or old" backup status

### Actual behaviour

Akeeba Backup becomes NOT CONNECTED and no longer shows the status of backups

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/35969533/dabaa192-9047-431f-9bff-d545c951358c)

### Panopticon version

1.1.0

### PHP version

8.2.14

### Database type

MariaDB

### Database version

10.3

### Browser

Chrome

**Comment by nikosdion** [comment]
This is normal, because saving a site goes through the same API initialisation as setting it up from scratch. Use the reconnect button which appears in the Site Information page to reconnect to the Akeeba Backup API.
