### ISSUE TITLE
suspect of problem

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#537]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

hi, i've running panopticon on the same server of my websites, i suspect with the last updates that panopticon shutdown mysql server after some hours or days from the last panopticon 1.1.0 update.
it is possible that panopticon interfere with the databes and shutdown mysql service?

the php version running is 8.2 and mysql version is 8.0.35

sql_management is the panopticon db from the logs below

### Screenshots

# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3479
# Query_time: 21659.808033  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980062;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.929374Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3494
# Query_time: 21539.824568  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980182;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.954405Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3503
# Query_time: 21419.843748  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980302;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.962091Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3534
# Query_time: 21119.844974  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980602;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.977758Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3567
# Query_time: 20819.852284  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980902;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.994976Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3574
# Query_time: 20759.859040  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705980962;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.995770Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3631
# Query_time: 20279.598565  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705981442;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:01.998229Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3647
# Query_time: 20159.592891  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705981562;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:02.014420Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3662
# Query_time: 20039.601373  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705981682;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:02.045097Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3719
# Query_time: 19439.615254  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705982282;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:02.281260Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3735
# Query_time: 19319.817004  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705982402;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:02.764693Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  3751
# Query_time: 19200.097904  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705982522;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:02.864134Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  4039
# Query_time: 18480.178111  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705983242;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:03.454193Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  4151
# Query_time: 18240.743121  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705983482;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:22:03.454217Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:  4551
# Query_time: 16321.222486  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1705985402;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
/www/server/mysql/bin/mysqld, Version: 8.0.35 (Source distribution). started with:
Tcp port: 3306  Unix socket: /tmp/mysql.sock
Time                 Id Command    Argument
/www/server/mysql/bin/mysqld, Version: 8.0.35 (Source distribution). started with:
Tcp port: 3306  Unix socket: /tmp/mysql.sock
Time                 Id Command    Argument
/www/server/mysql/bin/mysqld, Version: 8.0.35 (Source distribution). started with:
Tcp port: 3306  Unix socket: /tmp/mysql.sock
Time                 Id Command    Argument
# Time: 2024-01-23T09:38:06.327328Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:    31
# Query_time: 8.314240  Lock_time: 0.000029 Rows_sent: 0  Rows_examined: 0
use sql_management_t;
SET timestamp=1706002678;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:38:06.335927Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:    17
# Query_time: 8.193963  Lock_time: 0.000026 Rows_sent: 0  Rows_examined: 0
SET timestamp=1706002678;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;
# Time: 2024-01-23T09:38:06.345817Z
# User@Host: sql_management_t[sql_management_t] @ localhost []  Id:    50
# Query_time: 3.717265  Lock_time: 0.000027 Rows_sent: 0  Rows_examined: 0
SET timestamp=1706002682;
LOCK TABLES `pnptc_tasks` WRITE, `pnptc_tasks` AS `s` WRITE, `pnptc_sites` WRITE;

### Panopticon version

1.1.0

### PHP version

8.2

### Database type

MySQL

### Database version

8.0.35

### Browser

None

**Comment by morphinestyle** [comment]
It looks the same as this one: #535

**Comment by morphinestyle** [comment]
Also in my case I had to restart MariaDB, it never happened on the server, and it has already happened twice using Panopticon.

I don't know the causes, but the situation is starting to become significantly similar.

**Comment by nikosdion** [comment]
@Raxiel1987 Try using the latest `main` branch. Go to this repository's main page, click on Code, click Download ZIP. I have already made some changes to the way locking is performed. Instead of requesting a table lock we're now using a local lock which is released when the process terminates.

**Comment by nikosdion** [comment]
@Raxiel1987 Since you are getting an error about acquiring a lock, I think it may be related. 

In previous versions we were trying to get a table-level lock on the `#__tasks` table. However, under some circumstances, I saw that MySQL experienced a race condition and granted a lock to two different processes. This would cause problems running tasks as the same thing was running twice at the same time. I assume that this would also fail to release the lock due to a deadlock condition: two processes holding the same lock means that each process is waiting for the other one to release the lock, which it cannot do because the other process holds the same lock.

To avoid both the race condition and the deadlock I am now following a different approach. I acquire a named lock after waiting a random amount of time (in the order of 0.1 to 0.5 seconds), then check in the code if this lock is acquired by our process or not. If it's not, I go back into waiting for 5 seconds. This seems to work far better in half a dozen environments I have tried it so far, including my own production environment.

Even though I have not experienced a crashed MySQL, the fact that you have a report of a deadlock makes me think that your problem might indeed be what I noticed and fixed. So, let's try that and see how it works!

**Comment by morphinestyle** [comment]
I'll try it as soon as I can.

@Raxiel1987 yes, i'm italian and I am the translator of the Italian version of Panopticon. How can we get in touch?

**Comment by morphinestyle** [comment]
> you're doing good work translating panopticon

Thanks, there are two errors to correct in the next translations:
- Sistema di Debug → Debug di Sistema
- Riguardo → About (at the bottom of the page)

**Comment by nikosdion** [comment]
@Raxiel1987 You need to stop all of the Panopticon CRON jobs and wait for the tasks to finish. Then, restart the CRON jobs.

**Comment by nikosdion** [comment]
@Raxiel1987 We don't know if that process is running the new code. Kill it, and let the CRON start another process. If you still get the same issue, restart your database server.

**Comment by nikosdion** [comment]
@Raxiel1987 We don't know if that process is running the new code. Kill it, and let the CRON start another process. If you still get the same issue, restart your database server.

**Comment by nikosdion** [comment]
To make it even more clear, here's what the log entries from the current version look like:

```
2024-01-23 19:39:24.612 EET | INFO | task_runner | Locking task tables | [] | []
2024-01-23 19:39:24.613 EET | DEBUG | task_runner | Got tasks lock [30510] | [] | []
2024-01-23 19:39:24.613 EET | INFO | task_runner | Cleaning up stuck tasks | [] | []
2024-01-23 19:39:24.614 EET | INFO | task_runner | Getting next task | [] | []
2024-01-23 19:39:24.768 EET | INFO | task_runner | There are no pending tasks. | [] | []
2024-01-23 19:39:24.768 EET | DEBUG | task_runner | No tasks; waiting for 5 seconds. Time left before exiting: 47.9s | [] | []
2024-01-23 19:39:26.971 EET | INFO | task_runner | Locking task tables | [] | []
2024-01-23 19:39:26.972 EET | DEBUG | task_runner | Got tasks lock [30522] | [] | []
2024-01-23 19:39:26.972 EET | INFO | task_runner | Cleaning up stuck tasks | [] | []
2024-01-23 19:39:26.973 EET | INFO | task_runner | Getting next task | [] | []
2024-01-23 19:39:27.143 EET | INFO | task_runner | There are no pending tasks. | [] | []
2024-01-23 19:39:27.143 EET | DEBUG | task_runner | No tasks; waiting for 5 seconds. Time left before exiting: 105.1s | [] | []
```

The message "Got tasks lock" is new. The number next to it is the PID (process ID) of the PHP process in which the CRON task is running. If you see neither this message, nor "Could not obtain tasks lock" then you are still running the old code. If you are still running the old code, either your process is stuck, or you have another problem (did not overwrite the code, did not clean OPcache, etc). The solution to that is to stop all processes running the old code.

For example:

```bash
$ ps -A | grep php

54101 ??         0:00.01 /bin/sh -c /usr/bin/php /path/to/panopticon/cli/panopticon.php task:run --loop > /dev/null

$ kill -s SIGTERM 54101
```

You can then check if you have the right code, whether you need to restart any other PHP processes so that the opcache can be cleaned, and so on.

**Comment by nikosdion** [comment]
That was from the debug.log :)

**Comment by nikosdion** [comment]
Awesome! Thank you for the feedback :)
