### ISSUE TITLE
false message regarding SSL certificate

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#548]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Panopticon is reporting that the SSL certificate of multiple websites are invallid.
i checked them and all are good and valid.
in this case al the websites are shared hosting and using lets encrypt certificates.
some sites with same situation are not reporting invallid certificated.

### Reproduction instructions

on website overview a lock icon is shown

### Expected behaviour

it should not shown because certificate are vallid

### Actual behaviour

shows icon that certificated is invallid

### Panopticon version

1.10.0

### PHP version

several

### Database type

MySQL

### Database version

serveral

### Browser

Chrome

### Browser version

latest

**Comment by nikosdion** [comment]
This is exactly why I was reluctant to implement this feature. You are seeing a **WARNING** that the TLS certificate will be expiring soon. Since you never bothered to change the default setting, it reminds you a month in advance, long before `certbot` automatically updates your Let's Encrypt certificate.

You need to configure your sites to only warn you one day in advance instead of 30 days in advance.

**Comment by johanpeters** [comment]
Hello Nickolas,
i have checked the 2 sites with this issue.. 
both have valid certificated and configured that panopticon should notify 7 days prior to expiration date.
in this case the certificate is valid until 03-martch 2024.
the other certificate is valid until 04 april 2024.

**Comment by nikosdion** [comment]
Click on the site to get to its Site Information page. On the top right there's the SSL status icon. Click on it. What is the information reported?

For example, here's one of my live sites (serial and domain names changed for privacy):

```
Serial 	1234567890ABCDEF1234567890ABCDEF01234
Signature Type 	sha256WithRSAEncryption
Valid From 	Sunday, 21 January 2024 15:47:16 EET
Valid To 	Saturday, 20 April 2024 16:47:15 EEST
Common Names (domains) 	

    *.example.com
    example.com
    www.restored.example.com
    www.updates.example.com

Issued By 	Let's Encrypt – R3 
```

**Comment by johanpeters** [comment]
i reply'd on you gmail account with screenshots
