### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#549]
Putting this here so it doesn't get forgotten

Something is not correct with the code for the site favicon. No matter what I tried I only ever get the fallback globe

**Comment by nikosdion** [comment]
I already fixed it in 1.1.1 which was released minutes before your issue :)

**Comment by brianteeman** [comment]
I still only get the globe. :(

git pull
composer install
deleted tmp/
deleted site
added site

**Comment by nikosdion** [comment]
Just checking if this is resolved for you. If it is, please close the issue; I am doing a bit of a Spring cleanup :)

**Comment by brianteeman** [comment]
this issue is resolved so will close.
