### ISSUE TITLE
Ace Theme 

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#557]
I think the code from this commit https://github.com/akeeba/panopticon/commit/5015e639b5c462cbc3b26646fe2f122fb3431a27 to support light and dark modes is not correct.

If I check the browser console I have the following error

`Refused to create a worker from 'blob:https://panopticon.brianstest.site/cede2e20-5800-46e2-8843-a2e1bc842c83' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.`

and these warnings

misspelled option "themeLight"
misspelled option "themeDark"
Could not load worker DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://panopticon.brianstest.site/cede2e20-5800-46e2-8843-a2e1bc842c83' is denied by the document's Content Security Policy.

I think I know the reasoning for the misspelled option but not sure of the code to fix it.

**Comment by nikosdion** [comment]
The warning you get from ACE editor is irrelevant. I do store two non-standard options which is what allows me to dynamically switch from dark to light mode even though ACE does not have this feature.

The worker issue, I don't see this, nor do I see any workers in the network connections. Is it possible it is caused by some third party browser extension…?

**Comment by brianteeman** [comment]
I get the worker issue on my live server but not on my local server

**Comment by nikosdion** [comment]
Can you try commenting out the Content Security Policy section of your .htaccess file?

**Comment by brianteeman** [comment]
Yes it was the csp in the default htaccess file causing the issue

I didnt have the error on my local server as I had forgotten to enable htaccess
