### ISSUE TITLE
ssltlsexpiration task

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#562]
The status of this task says

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON) * 1 DAY) <= NOW()) AND \n(JSON_EXTRACT(config, '$.auto_email.ssl.serial'...' at line 4`

**Server Info**
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.5.22-MariaDB - MariaDB Server
Protocol version: 10

**Comment by nikosdion** [comment]
Thanks! There is a weird difference between the way MariaDB and MySQL deal with JSON values. In MySQL you have to cast as either JSON or FLOAT for the value to be usable in the context of an INTERVAL. In MariaDB you have to cast as either INTEGER or FLOAT. And just to think that the JSON code in MariaDB comes from their fork off MySQL…

**Comment by brianteeman** [comment]
Confirming that the fix resolves the issue
