### ISSUE TITLE
Incompatibility report

### ISSUE THREAD

**Issue by Freewindrider** [akeeba/panopticon#569]
Hej,

If you have the EasyBlog User Plugin installed AND activated on a website, Panopticon will be unable to connect to the respective installation. Any attempts result in an Error 500.

**Noone here needs to correct or do anything.** The StackIdeas plugin is outdated and should be refactored. 
![user-plugin-easyblog](https://github.com/akeeba/panopticon/assets/28390531/f4dd0c09-3f9f-4edb-8a3f-b2129a0af839)

When the StackIdeas-plugin is deactivated, Panopticon works as intended and the connection to the Joomla-installation can be established without any problems. In case support-requests will be raised...

**Comment by nikosdion** [comment]
Thank you.

I have seen that before, and it's definitely not the only thing they break. We've had reports about our paid Joomla! software getting broken by this plugin as well.

Other users have asked them to contact us, they never bothered, so my official recommendation now is **do NOT use StackIdeas software in Joomla!, it will break your site, and they don't even care to fix anything**.
