### ISSUE TITLE
version.php missing ?

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#57]
can't find the version.php to proceed with installation.

https://github.com/akeeba/panopticon/blob/07912735745370bb95aa86afdd2c45564639bc12/index.php#L16C2-L16C2

Was it accidentally added to .gitignore or did I miss a build step in the documentation?

**Comment by nikosdion** [comment]
Ah, good catch! When I’m back home later today I’ll see what’s going on. This is automatically generated by the build script and you’re right it should be either included in the repo or generated when you do composer install.

**Comment by brianteeman** [comment]
Ping me when its added and I will take a look further.

**Comment by nikosdion** [comment]
Just run `git pull; composer install` and the file will be auto-generated.

**Comment by brianteeman** [comment]
just confirming that the version.php is now created
