### ISSUE TITLE
Another incompatibility report

### ISSUE THREAD

**Issue by Freewindrider** [akeeba/panopticon#574]
Another incompatibility report: When the system plugin ZOOlingual by ZOOlanders is installed and activated, any attempts to access the Joomla API result in an error 500.

![image](https://github.com/akeeba/panopticon/assets/28390531/9ab177af-bc52-420c-8439-166a746881be)

As soon as the plugin is deactivated, the API can be accessed without problems and Panopticon is able to reach the respective site/installation.
It is NOT a Panopticon issue and I've informed the developers about this wrong feature behaviour.

**Comment by Freewindrider** [comment]
This has been fixed by the developers with version 2.1.6 (February 22, 2024) and I tested the fix successfully. 
https://zoolanders.com/essentials-for-zoo/changelog

**Comment by nikosdion** [comment]
Thank you for the heads up!
