### ISSUE TITLE
SVG images in emails

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#576]
By default all the emails have an svg image of the panopticon logo in the header. Unfortunately the use of svg images in gmail is not supported (https://www.caniemail.com/features/image-svg/) and will not be fixed (https://til.hashrocket.com/posts/rynww6hwyy-do-not-serve-svg-images-in-email-content)

We can either replace the svg in the email with a jpg or png, document that svg will not be displayed in gmail or do nothing.

Thoughts?

**Comment by nikosdion** [comment]
I guess we can change the default data to a PNG, but it will have to be the white-only logo we normally use in dark mode (otherwise dark mode looks weird). This does not solve the problem for existing installations, but that's a very minor issue.

Would you care doing the PR for that?

**Comment by nikosdion** [comment]
Thank you!

**Comment by brianteeman** [comment]
Maybe I am missing something but I cant find the png you refer to.

I also can't find the 3 files referenced here
```
        <link rel="icon" type="image/png" href="<?= $this->include('assets/images/favicon.png.base64'); ?>">
        <style><?= $this->include('assets/css/exception.css'); ?></style>
        <style><?= $this->include('assets/css/exception_full.css'); ?></style>
```

**Comment by nikosdion** [comment]
The three icons you noted are NOT part of Panopticon, they are part of Symfony ErrorHandler. The `assets` folder referenced is the `vendor/symfony/error-handler/Resources/assets` in Panopticon (after installing dependencies). Remember, I am doing forbidden dark magic to customise the look of Symfony's error handler.

As for the PNGs, let me do a conversion and commit it. It should be ready in 5'.
