### ISSUE TITLE
CRON job error

### ISSUE THREAD

**Issue by Pierre-AmultisDev** [akeeba/panopticon#578]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Received this error message in the mail.

[error] Task failed with exception type mysqli_sql_exception [/home/u145233p137455/domains/tst-web.nl/public_html/sitemonitoring/vendor/akeeba/awf/src/Database/Driver/Mysqli.php:373]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON) * 1 DAY) <= NOW()) AND (JSON_EXTRACT(config, '$.auto_email.ssl.serial'...' at line 4 PHP Deprecated:  Calling Awf\Application\Application::getInstance is deprecated. Go through the Container instead. in /home/u145233p137455/domains/tst-web.nl/public_html/sitemonitoring/vendor/akeeba/awf/src/Application/Application.php on line 147

### Reproduction instructions

Removed the 2>&1 at the end of the cron job statement to receive error messages.

### Expected behaviour

No error messages

### Actual behaviour

Received the error message in the mail

### Panopticon version

1.1.1

### PHP version

8.1.24 

### Database type

MariaDB

### Database version

10.4.27-MariaDB-cll-lve 

### Browser

Firefox

### Browser version

122.0.1

**Comment by nikosdion** [comment]
Duplicate gh-562 and already fixed.
