### ISSUE TITLE
em-dash

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#58]
Couldnt work out why some of your text was so strange for me to read. Its the use of the em-dash.

https://getproofed.com.au/writing-tips/en-dashes-and-em-dashes-in-us-and-uk-english/

> The main difference is that US English uses em dashes—usually without spaces—in place of parentheses, while UK English prefers the shorter en dash – with a space either side – for the same purpose.

![image](https://github.com/akeeba/panopticon/assets/1296369/96997e82-3f5a-4216-bf4a-c0ddc6452e6d)

**Comment by nikosdion** [comment]
I guess all the writing guides I read were US-centric. Would you please make these changes and send a PR?

**Comment by nikosdion** [comment]
Pro tip: you don’t need to close the ticket when you submit a PR. Just add the text Closes #whatever or Closes gh-whatever in the PR text. When the PR is merged the issue closes. This is better for project management as you can see which issues are still pending despite an unmerged PR existing. Joomla is using GitHub wrong; I prefer to use it as it was intended to be used.
