### ISSUE TITLE
All backup schedules are disabled since last Joomla Update

### ISSUE THREAD

**Issue by Martin511** [akeeba/panopticon#581]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Since the last backup before update to Joomla 4.4.3 / 5.0.3 all my backup schedules in Panopticon are disabled.
Is that a bug?

### Reproduction instructions

1. Go to …
2. Click on …
3. Scroll down to …

### Expected behaviour

Backups should be triggered as set in schedule.

### Actual behaviour

No backups are triggered.

### Panopticon version

1.1.1

### PHP version

8.2.13

### Database type

MariaDB

### Database version

10.5.23

### Browser

None

**Comment by nikosdion** [comment]
What does one thing have to do with another? Nothing.

Your backup schedules are controlled entirely by Panopticon. They will not get disabled automatically.

**Comment by Martin511** [comment]
I´m just looking for help. All backup schedules _are_ disabled for 25 sites.
Is it possible that they have been deactivated alltogether by one click accidentially?

**Comment by Martin511** [comment]
I can confirm this.
![Screenshot 2024-02-23 091224](https://github.com/akeeba/panopticon/assets/56762649/fa94efd0-ffc5-4f6d-bcad-f62ee1747a8d)

**Comment by nikosdion** [comment]
If you enable it, does it run?

After it runs, does it stay enabled?

**Comment by Martin511** [comment]
Yes, after I enabled it manually, the missed backup from 21 February was immediately made up for and so far it remains activated. 
I would just love to know why all my backups were deactivated at one point in time.
Strange.

**Comment by nikosdion** [comment]
Beats me. We only have code to disable tasks designated as Run Once. The scheduled backup task is NOT designated as such. Apart from disabling tasks in the interface, the only other possibility is messing directly with the database.

**Comment by Martin511** [comment]
OK, so I will click through all my sites and enable the schedule again and see what the future brings.
Seems that I´m the only one facing this so it does not seem to be a general issue. 🤷🏻‍♂️

Are there any log files I can provide that could help you to investigate deeper?

**Comment by nikosdion** [comment]
I can't think of any log file which would help with that. As I said, the only place where we change the status of a task is the task runner and it only triggers for one-off tasks. No other tasks (like refreshing the site information) gets disabled, so whatever it is does not come from there, therefore it's not logged.

**Comment by nikosdion** [comment]
Since there's been a new update for Joomla recently, have you observed the same behaviour or did everything worked correctly?

**Comment by Martin511** [comment]
I´m confused. The last known update was the Joomla 5.0.3 and 4.4.3 Security and Bug Fix Release on February 20th.
I don´t know about any new updates since.

**Comment by nikosdion** [comment]
Sorry, I thought your ticket predated that update.

**Comment by conseilgouz** [comment]
Hi,

I have the same issue. 

I think it's coming from src/Task/JoomlaUpdateDirector.php, line 167 to 172 where panopticon set enabled to 0 in task table.

This is supposed to block other joomlaupdate tasks, but it blocks all tasks from on site.

Maybe add type = 'joomlaupdate' in where condition will solve this.
