### ISSUE TITLE
Cancellation of operation results in error 500 for some usergroups

### ISSUE THREAD

**Issue by Freewindrider** [akeeba/panopticon#583]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

The cancellation of i.e. site configuration changes for users NOT having superuser-rights (acl) results in an error 500.

Akeeba\Panopticon\Library\User\User::getContainer(): Return value must be of type Awf\Container\Container, null returned
in src/Library/User/User.php line 59: $site = $this->getContainer()->mvcFactory->makeTempModel('Site')

**This only happens for users not having the right to view all sites configured in Panopticon (users with limited rights).**

### Reproduction instructions

1. Go to a website-configuration, make sure to be logged in with a user having only the rights to view/edit own sites.
2. Click on the cancel-button to return to the dashboard.
3. The error shows up immediately.

### Expected behaviour

The dashboard with the user-sites loads without errors.

### Actual behaviour

Error 500, Akeeba\Panopticon\Library\User\User::getContainer(): Return value must be of type Awf\Container\Container, null returned
src/Library/User/User.php (line 59)

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/28390531/5bdadd22-e75f-4fd3-b950-bba5a85c8a65)

### Panopticon version

1.1.1

### PHP version

8.2.13

### Database type

MariaDB

### Database version

10.6.16

### Browser

None

**Comment by nikosdion** [comment]
Thank you!
