### ISSUE TITLE
cron error PHP Deprecated:  Calling Awf\Application\Application::getInstance is deprecated.

### ISSUE THREAD

**Issue by Pierre-AmultisDev** [akeeba/panopticon#611]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

After upgrading to Panopticon 1.1.2 still cron error mesage:
PHP Deprecated:  Calling Awf\Application\Application::getInstance is deprecated. Go through the Container instead. in /home/<<USER>>/domains/tst-web.nl/public_html/sitemonitoring/vendor/akeeba/awf/src/Application/Application.php on line 158

### Reproduction instructions

Removed the 2>&1 at the end of the cron job statement to receive error messages.

### Expected behaviour

No error messages

### Actual behaviour

Received the error message in the mail

### Panopticon version

1.1.2

### PHP version

8.1.24

### Database type

MariaDB

### Database version

10.4.27-MariaDB-cll-lve

### Browser

Firefox

### Browser version

122.0.1

**Comment by nikosdion** [comment]
It's not an error, it's a user deprecation notice. Don't worry, I know about it. I have written both Panopticon, and AWF. Changing the Application object requires some refactoring which is not scheduled until version 2.

**Comment by Pierre-AmultisDev** [comment]
Thank you, for the swift reply.
