### ISSUE TITLE
menu divider

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#63]
When you have a menu item divider the `li ` must have a `role="presentation"

![image](https://github.com/akeeba/panopticon/assets/1296369/60c221b1-ca40-4fb6-9572-495d92f414de)

If it doesn't then the screenreader will announce there are 9 links and this is link 3 of 9 when in fact it is 2 of 6. Obviously it will confuse the user if it says there are 9 links but the screenreader can only _see_ 6

Yes: This is a bug in the bootstrap documented examples.

**Comment by nikosdion** [comment]
Luckily, I had written the code in a way that anticipate a change like that. I remembered there was something off about Bootstrap's code examples for drop-downs but I did not remember exactly _what_ 🤣
