### ISSUE TITLE
core and module update information fail

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#634]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

on several sites i have errors regarding update information.
its on J3 and J4 sites. not al sites running J3 or J4 having this issue

### Reproduction instructions

1. login
2. on main page click on refresh button on version update information
3. result in error and exlamation pointer

### Expected behaviour

i would expect that the update information is up-to-date / received

### Actual behaviour

several errors 

### Screenshots

![Schermafbeelding 2024-04-20 om 06 27 03](https://github.com/akeeba/panopticon/assets/1411354/ba5df035-17a3-4eca-90c8-2ccf87791860)
![Schermafbeelding 2024-04-20 om 06 28 04](https://github.com/akeeba/panopticon/assets/1411354/aa0a2bd3-d30d-472e-86af-90e9b950171a)
![Schermafbeelding 2024-04-20 om 06 36 01](https://github.com/akeeba/panopticon/assets/1411354/f9e71399-4346-4a10-bc3c-12d9b6e6b4dd)

### Panopticon version

1.1.4

### PHP version

8.1.2

### Database type

MySQL

### Database version

8.0

### Browser

Chrome

### Browser version

latest

**Comment by nikosdion** [comment]
The first screenshot shows a timeout. You just have too many extensions. Forcing an update of their status takes longer than 30 seconds and the request times out. This is how Joomla works and you may end up seeing a timeout like that on many servers if you reset the uodste info in Joomla and then try to fetch updates. I cannot make worldwide Internet faster. Use less extensions, or don't use this button on this site. When update info is retrieved per extension it will take less time and things will work fine. The second screenshot tells me that a third party plug-in cocks up by assuming every request is an HTML request. Nothing I can do over here either, it is not my code. Nicholas K. DionysopoulosLead developer and directorAkeeba LtdSent from a mobile device. Please excuse typos and brevity.
