### ISSUE TITLE
tinymce source code view

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#64]
I was looking to see why the images were not displaying in the mailtemplate previews and found this when in tinymce source code view

I guess there is a height value missing?

![image](https://github.com/akeeba/panopticon/assets/1296369/d9da0e9c-6c2a-44b0-b79d-983904605511)

**Comment by nikosdion** [comment]
I think this is a conflict between Bootstrap and TinyMCE styling. I added a very hacky workaround because I can't find a better way to do it and it's really not worth spending too much time on it.
