### ISSUE TITLE
One text line missing in .POT for translation

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#641]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

I have some text that still appears in English, but doesn't appear in the current .POT:
"Leave empty if you do not wish to change the password of this user account."
You find it in "Edit User" as description under the password field.
At least, you can´t translate it, ´cause there is no string in .POT (or in en-GB.ini).

### Reproduction instructions

1. Go Administration
2. Go to User
3. Click on Username
4. Scroll down to Password

### Expected behaviour

Translated text, if I can find the string for it.

### Actual behaviour

No translation of the described string.

### Screenshots

![trans_missing](https://github.com/akeeba/panopticon/assets/26506313/d8fa8b26-bce7-4e7d-ad63-80942ac894bb)

### Panopticon version

1.1.3 (with new de-DE.po)

### PHP version

8.3.6

### Database type

MariaDB

### Database version

??

### Browser

Edge

### Additional information

This problem occurs when you use the current Panopticon with the newly published de-DE.po language file and create the .ini file as described in the instructions.
There seems to be a translation string missing from the .POT file.

**Comment by nikosdion** [comment]
A lot more will be added, hopefully relatively soon, as I am working on WordPress compatibility. I am holding off updating the POT until then (otherwise I get a ton of merge conflicts between the branches...).

**Comment by NetSecond** [comment]
Ok, thanks.

**Comment by NetSecond** [comment]
So, I will fix it, see Pull Requests later ....

**Comment by NetSecond** [comment]
.POT file and associated files corrected, supplemented and tested.

Please check an close issue when ok ....

**Comment by NetSecond** [comment]
Found another missing string.
I fixed and tested it / ok ....
Sorry for the extra work.
I only saw it shortly afterwards when I tested everything again.

**Comment by NetSecond** [comment]
Closed because fixed.
