### ISSUE TITLE
mfa

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#68]
Setup a passkey
Try to disable mfa ==> 403
Try to delete passkey ==> 500 invlaid token

tried to update the ACLTrait to fix this but either it wasn't that or I did it wrong

**Comment by nikosdion** [comment]
For the 403: I have not written that code yet 😛 I got busy with the house renovation and didn't have until this week.

For the 500: You are right, it is missing the token.

I'll fix both of these.
