### ISSUE TITLE
Error when upgrade from 1.1.2 to1.1.3

### ISSUE THREAD

**Issue by brainyNL** [akeeba/panopticon#686]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

In Panopticon, when I click on the button 'upgrade', I see this page immediately;

error:; Undefined constant ZipArchive::RDONLY

plus some code;
          ini_set('memory_limit', '1024M');        }        $zip = new ZipArchive();        switch ($zip->open($sourceFile, ZipArchive::RDONLY))        {            case ZipArchive::ER_INCONS:                /**                 * Ignore this. Despite open() returning this error it can still open and extract the archive. Yeah.                 */ // throw new RuntimeException(sprintf('Update file %s is inconsistent.', $sourceFile));

Where can I find more info about how to handle this issue?

Kind regards, Hein

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/86366984/b6500a4b-dabf-4666-895e-86c8ae3d5a5f)

### Panopticon version

1.1.2

### PHP version

 8.2.18

### Database type

MariaDB

### Database version

10.4.33

### Browser

Chrome

### Browser version

125.0.6422.77

**Comment by nikosdion** [comment]
Show this to your host, and ask them how to enable the PHP Zip extension.
