### ISSUE TITLE
Building the connectors

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#70]
thanks for the docs

after a stupidly long time messing about with versions on my server I managed to complete the creation of a connector. maybe its implied in your docs but I found that I had to explicitly composer install the buildfiles.git repo

**Comment by brianteeman** [comment]
spoke too soon
![image](https://github.com/akeeba/panopticon/assets/1296369/3c879371-9253-40f5-8054-27fd576b1058)

**Comment by brianteeman** [comment]
and composer install the connectors as well.

**Comment by nikosdion** [comment]
Good catch and thank you for beta testing the docs, not just the software 😬 I'm going to add these points there now.

**Comment by brianteeman** [comment]
full service testing from me :)
