### ISSUE TITLE
Why are the new .INI changes not in .POT ??

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#711]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

There are new translations in gb.ini file, that are not in .po or .pot file ?!?!
Is there any reason why ??

When I generate de.ini file with .po and .pot file, there are missing a lot of new translations like in last updated .ini files here in GitHub ....

### Panopticon version

1.1.3

### PHP version

8.3.8

### Database type

MariaDB

### Database version

??

### Browser

None

**Comment by nikosdion** [comment]
Which branch?

**Comment by NetSecond** [comment]
Main.

I found differences about new Batch and Docker for e.x. ....

**Comment by nikosdion** [comment]
These have not been transferred yet to the POT. I am working on WordPress integration with priority right now, hopefully will be able to merge it by end of July and regenerate the POT.

**Comment by NetSecond** [comment]
Ok, thanks, then I will wait with changes in the de.ini.

**Comment by NetSecond** [comment]
@nikosdion
I expanded the current .pot file to include the entries from the English .ini file and published it as a pull request.

If you have time, you can take a look at it.

If further changes follow or this extension no longer fits, please close the pull request with a short note.

Best regards
Net

**Comment by nikosdion** [comment]
As I said:

> hopefully will be able to merge it by end of July and regenerate the POT.

I don't want to create a new POT just yet because I _know_ there are language changes coming in from the merge. I don't want to create double work for you, and a lot of headaches for me trying to merge PO files in languages I don't speak :)

**Comment by NetSecond** [comment]
Ok, no problem, do as you think and we'll be ready when there's something to translate again.
Thanks for the hard work and the great script and best regards
Net

**Comment by nikosdion** [comment]
Give it a week or so. I have made a lot of progress over the last week ;)

**Comment by NetSecond** [comment]
You're fantastic, I'm excited.
