### ISSUE TITLE
Use input[type=time] for the “Time Of The Day to Install Updates On” field

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#72]
![image](https://github.com/akeeba/panopticon/assets/1296369/9b2aabde-6476-4a9d-8088-8f4d8419350f)

There is only a label on the first of these two fields (hours)

Did a quick search and found these patters that might be better to use https://thepaciellogroup.github.io/AT-browser-tests/test-files/input-time.html

So perhaps

```
<label for="timeofday">
	Time Of The Day to Install Updates On (Hour:Minute)
</label>
<input id="timeofday" type="time" aria-describedby="timeofdaydesc">
<div class="form-text" id="timeofdaydesc">
            The time expressed in the GMT timezone. If updates are found <em>after</em> this time of the day the update installation will take place in the next calendar day. Avoid using the Daylight Savings Time changeover time of the day (usually: between 2am and 4am); otherwise, update scheduling will act in what you perceive to be a “weird” or “wrong” way if an update is found on the day of the Daylight Savings Time changeover.        
</div>

```

just a suggestion

**Comment by nikosdion** [comment]
I am already aware of the time field. Unfortunately, the time input is not a good fit _yet_, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#handling_browser_support 

Right now, it leaves behind some older Macs. This will become less relevant in a year or so and I can move to the time field and a bit of post-processing in the Controller to normalise what it returns back to us. This was always the idea, so I am tagging this as Planned.

**Comment by brianteeman** [comment]
In the meantime you can do it as a fieldset 
```
<fieldset>
	<legend id="timeofday">Time Of The Day to Install Updates On (Hour:Minute)</legend>
	<input id="hours" type="text" aria-describedby="timeofdaydesc">
	<label for="hours" class="sr-only">Hours</label>
	<input id="mins" type="text" aria-describedby="timeofdaydesc">
	<label for="mins" class="sr-only">Minutes</label>
</fieldset>
```
