### ISSUE TITLE
Missing translation string in admin panel (.pot and .po)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#751]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Missing translation string in .pot and .po in admin panel:

Administration => System Configuration => System => System Preferences => under Error Reporting:
Text under "Behind load balancer / reverse proxy":

`Only enable if your installation is behind a non-transparent proxy (e.g. Varnish), load balancer (e.g. HAProxy), CDN (e.g. CloudFlare), or security service (e.g. Sucuri) which conveys the real IP address of the visitor through the HTTP header X-Forwarded-For.`

This text does not exist in .pot and .po files.
In all language it shows only the english source text.

EDIT:
Found missing string in gb.ini:
`PANOPTICON_SYSCONFIG_LBL_FIELD_BEHIND_LOAD_BALANCER_HELP`
/EDIT

### Reproduction instructions

Administration => System Configuration => System => System Preferences

### Expected behaviour

Correct translated text.
(In case of no source in .pot/.po, there is nothing found to translate.)

### Actual behaviour

No matter which language is set, English is displayed.

EDIT 2:
Added Pull Request with corrected panopticon.pot.
/EDIT 2

**Comment by nikosdion** [comment]
Thank you!
