### ISSUE TITLE
After update to 1.2.1 i get "Error: Value of type null is not callable in" when you click on the site name on the Dashboard -- only on Joomla Websites

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#754]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

When I click Joomla site names on Panopticon dashboard it gives this error

### Reproduction instructions

Click a Joomla site name on Panopticon dashboard

### Expected behaviour

Enter the selected site screen

### Actual behaviour

I have this error:

`Error: Value of type null is not callable in /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php:423 Stack trace: #0 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1301): include() #1 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile() #2 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #3 /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/8/f/8f7c002723e6e58319c2bd5cc86d45be63532969.php(112): Awf\Mvc\View->loadAnyTemplate() #4 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1301): include('...') #5 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile() #6 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #7 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate() #8 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate() #9 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #10 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #11 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #12 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute() #13 /MY_WEBSITE_ROOT/public_html/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute() #14 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute() #15 /MY_WEBSITE_ROOT/public_html/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #16 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #17 /MY_WEBSITE_ROOT/public_html/src/Application.php(430): Awf\Application\Application->dispatch() #18 /MY_WEBSITE_ROOT/public_html/index.php(35): Akeeba\Panopticon\Application->dispatch() #19 /MY_WEBSITE_ROOT/public_html/index.php(38): {closure}() #20 {main} Next RuntimeException: Error calling repeatable "extUpdateExtensionIcon" in /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php:423 Stack trace: #0 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1301): include() #1 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile() #2 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #3 /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/8/f/8f7c002723e6e58319c2bd5cc86d45be63532969.php(112): Awf\Mvc\View->loadAnyTemplate() #4 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1301): include('...') #5 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile() #6 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #7 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate() #8 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate() #9 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #10 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #11 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #12 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute() #13 /MY_WEBSITE_ROOT/public_html/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute() #14 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute() #15 /MY_WEBSITE_ROOT/public_html/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #16 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #17 /MY_WEBSITE_ROOT/public_html/src/Application.php(430): Awf\Application\Application->dispatch() #18 /MY_WEBSITE_ROOT/public_html/index.php(35): Akeeba\Panopticon\Application->dispatch() #19 /MY_WEBSITE_ROOT/public_html/index.php(38): {closure}() #20 {main} Next ErrorException: Error calling repeatable "extUpdateExtensionIcon" [View template: ROOT/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php line 423, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php] in /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php:423 Stack trace: #0 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1235): Awf\Mvc\View->handleViewException() #1 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #2 /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/8/f/8f7c002723e6e58319c2bd5cc86d45be63532969.php(112): Awf\Mvc\View->loadAnyTemplate() #3 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1301): include('...') #4 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile() #5 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #6 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate() #7 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate() #8 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #9 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #10 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #11 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute() #12 /MY_WEBSITE_ROOT/public_html/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute() #13 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute() #14 /MY_WEBSITE_ROOT/public_html/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #15 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #16 /MY_WEBSITE_ROOT/public_html/src/Application.php(430): Awf\Application\Application->dispatch() #17 /MY_WEBSITE_ROOT/public_html/index.php(35): Akeeba\Panopticon\Application->dispatch() #18 /MY_WEBSITE_ROOT/public_html/index.php(38): {closure}() #19 {main} Next ErrorException: Error calling repeatable "extUpdateExtensionIcon" [View template: ROOT/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php line 423, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php] in /MY_WEBSITE_ROOT/public_html/tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php:423 Stack trace: #0 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(1235): Awf\Mvc\View->handleViewException() #1 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate() #2 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate() #3 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate() #4 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #5 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #6 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #7 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute() #8 /MY_WEBSITE_ROOT/public_html/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute() #9 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute() #10 /MY_WEBSITE_ROOT/public_html/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #11 /MY_WEBSITE_ROOT/public_html/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #12 /MY_WEBSITE_ROOT/public_html/src/Application.php(430): Awf\Application\Application->dispatch() #13 /MY_WEBSITE_ROOT/public_html/index.php(35): Akeeba\Panopticon\Application->dispatch() #14 /MY_WEBSITE_ROOT/public_html/index.php(38): {closure}() #15 {main}
`

### Panopticon version

1.2.1

### PHP version

8.2.18

### Database type

MariaDB

### Database version

10.11.7

### Browser

None

**Comment by nikosdion** [comment]
Operrn the file `tmp/compiled_templates/5/b/5b329751fafcd27f04906b25816c972e865e8067.php`. At the top it tells you which file it was compiled from. Which file is that?

Also, when you paste a stack trace **PLEASE**, for the love of what's holly, use [a code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) so that newlines are preserved. What you've pasted is a word soup I would have to spend about 10 minutes formatting just to read it. Show some mercy…

**Comment by morphinestyle** [comment]
I'm sorry for missing formatting.

This is the file:
`<?php /* /MY_WEBSITE_ROOT/public_html/ViewTemplates/Sites/item_extensions.blade.php */ ?>
`

**Comment by nikosdion** [comment]
Based on the trace you posted, your `vendor/akeeba/awf` folder is out of date. I have checked this is not a packaging error; I have a production system which got updated and I can use it just fine. This tells me it's either a partial upgrade (for reasons unknown; every way I can think it can fail is already caught in the code), or the PHP OPcache not resetting its cached content despite us telling it to.

Let's try to fix the former:

* Download the Panopticon 1.2.1 installation ZIP file.
* Extract it locally.
* Delete the entire `vendor` folder from your live installation.
* Delete the `tmp/compiled_templates` folder from your live installation.
* Upload the files you extracted.

If it still doesn't work, ask your host how you can reset the PHP OPcache.

**Comment by morphinestyle** [comment]
Yes, after uploading the files again it works fine now.
Thanks Nicholas!

**Comment by nikosdion** [comment]
You're welcome!
