### ISSUE TITLE
Error when viewing a Joomla site from the Overview page

### ISSUE THREAD

**Issue by ThreeCatsMarketing** [akeeba/panopticon#755]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

Clicking on a Joomla site from the Overview page gives the following error. WordPress sites are fine.

Error: Value of type null is not callable in /home/threecatsd/panopticon/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php:423 Stack trace: #0 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1301): include() #1 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile(Array) #2 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #3 /home/threecatsd/panopticon/tmp/compiled_templates/f/1/f1cec372dd54470c035bda55fdd7268fab6e837c.php(112): Awf\Mvc\View->loadAnyTemplate('Sites/item_exte...') #4 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1301): include('/home/threecats...') #5 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile(Array) #6 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #7 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate('Sites/item') #8 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate(NULL) #9 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #10 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #11 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #12 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute('read') #13 /home/threecatsd/panopticon/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute('read') #14 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute('read') #15 /home/threecatsd/panopticon/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #16 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #17 /home/threecatsd/panopticon/src/Application.php(430): Awf\Application\Application->dispatch() #18 /home/threecatsd/panopticon/index.php(35): Akeeba\Panopticon\Application->dispatch() #19 /home/threecatsd/panopticon/index.php(38): {closure}() #20 {main} Next RuntimeException: Error calling repeatable "extUpdateExtensionIcon" in /home/threecatsd/panopticon/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php:423 Stack trace: #0 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1301): include() #1 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile(Array) #2 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #3 /home/threecatsd/panopticon/tmp/compiled_templates/f/1/f1cec372dd54470c035bda55fdd7268fab6e837c.php(112): Awf\Mvc\View->loadAnyTemplate('Sites/item_exte...') #4 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1301): include('/home/threecats...') #5 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile(Array) #6 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #7 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate('Sites/item') #8 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate(NULL) #9 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #10 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #11 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #12 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute('read') #13 /home/threecatsd/panopticon/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute('read') #14 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute('read') #15 /home/threecatsd/panopticon/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #16 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #17 /home/threecatsd/panopticon/src/Application.php(430): Awf\Application\Application->dispatch() #18 /home/threecatsd/panopticon/index.php(35): Akeeba\Panopticon\Application->dispatch() #19 /home/threecatsd/panopticon/index.php(38): {closure}() #20 {main} Next ErrorException: Error calling repeatable "extUpdateExtensionIcon" [View template: ROOT/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php line 423, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php] in /home/threecatsd/panopticon/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php:423 Stack trace: #0 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1235): Awf\Mvc\View->handleViewException(Object(RuntimeException), 2) #1 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #2 /home/threecatsd/panopticon/tmp/compiled_templates/f/1/f1cec372dd54470c035bda55fdd7268fab6e837c.php(112): Awf\Mvc\View->loadAnyTemplate('Sites/item_exte...') #3 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1301): include('/home/threecats...') #4 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1231): Awf\Mvc\View->includeTemplateFile(Array) #5 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #6 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate('Sites/item') #7 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate(NULL) #8 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #9 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #10 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #11 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute('read') #12 /home/threecatsd/panopticon/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute('read') #13 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute('read') #14 /home/threecatsd/panopticon/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #15 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #16 /home/threecatsd/panopticon/src/Application.php(430): Awf\Application\Application->dispatch() #17 /home/threecatsd/panopticon/index.php(35): Akeeba\Panopticon\Application->dispatch() #18 /home/threecatsd/panopticon/index.php(38): {closure}() #19 {main} Next ErrorException: Error calling repeatable "extUpdateExtensionIcon" [View template: ROOT/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php line 423, compiled from ROOT/ViewTemplates/Sites/item_extensions.blade.php] in /home/threecatsd/panopticon/tmp/compiled_templates/0/6/06ca890647fae79a9d49d5688046543da3ff2337.php:423 Stack trace: #0 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(1235): Awf\Mvc\View->handleViewException(Object(ErrorException), 1) #1 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(745): Awf\Mvc\View->processTemplate(Array) #2 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(638): Awf\Mvc\View->loadAnyTemplate('Sites/item') #3 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/View.php(562): Awf\Mvc\View->loadTemplate(NULL) #4 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(447): Awf\Mvc\View->display() #5 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(113): Awf\Mvc\Controller->display() #6 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/Controller.php(375): Awf\Mvc\DataController->read() #7 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute('read') #8 /home/threecatsd/panopticon/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute('read') #9 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute('read') #10 /home/threecatsd/panopticon/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch() #11 /home/threecatsd/panopticon/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch() #12 /home/threecatsd/panopticon/src/Application.php(430): Awf\Application\Application->dispatch() #13 /home/threecatsd/panopticon/index.php(35): Akeeba\Panopticon\Application->dispatch() #14 /home/threecatsd/panopticon/index.php(38): {closure}() #15 {main}

### Panopticon version

1.2.1

### PHP version

8.3.9

### Database type

MySQL

### Database version

8.0.39

### Browser

Edge

### Browser version

127.0.2651.74

**Comment by nikosdion** [comment]
I believe [this will work for you too](https://github.com/akeeba/panopticon/issues/754#issuecomment-2254204017).
