### ISSUE TITLE
Failed adding a Joomla site

### ISSUE THREAD

**Issue by stefanschulz** [akeeba/panopticon#767]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

Hi,

I just installed Panopticon and all is green.
When I try to add my first Joomla site, I get the following error message (the overall message says, there is no error code):
Akeeba\Panopticon\Exception\SiteConnection\WebServicesInstallerNotEnabled

I configured the debug mode and got the following response/info:

### HTTP-Status
- 404

### HTTP-Body
- {"errors":[{"title":"Resource not found","code":404}]}

### HTTP HEADERS	
Server
- nginx

Date
- Sat, 10 Aug 2024 15:33:43 GMT

Content-Type
- application/vnd.api+json; charset=utf-8

Transfer-Encoding
- chunked

Connection
- keep-alive

x-frame-options
- SAMEORIGIN

referrer-policy
- unsafe-url

cross-origin-opener-policy
- same-origin

Expires
- Wed, 17 Aug 2005 00:00:00 GMT

Cache-Control
- no-store, no-cache, must-revalidate, post-check=0, pre-check=0
- no-transform

Pragma
- no-cache

Last-Modified
- Sat, 10 Aug 2024 15:33:43 GMT

X-Content-Type-Options
- nosniff

X-XSS-Protection
- 1; mode=block

Not sure, if this is a bug or some mis-configuration issue.

Thanks and all the best,
Stefan

### Panopticon version

1.2.1

### PHP version

8.2.22

### Database type

MariaDB

### Database version

10.11.9

### Browser

Chrome

### Browser version

127.0.6533.100

**Comment by nikosdion** [comment]
You have forgotten to activate a core Joomla! plugin, "Web Services - Installer".

For more information please refer to https://github.com/akeeba/panopticon/wiki/Connection-Troubleshooting#disabled-api-application-webservices-plugins-or-api-authentication-plugins
