### ISSUE TITLE
POEdit no longer detects new strings

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#770]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

POEdit no longer updates my language with new strings to translate added to Panopticon.pot.

For example, missing:
**msgctxt "PANOPTICON_SYSCONFIG_LBL_FIELD_AVATARS"
msgid "Show avatars for users"**
But many are missing.

I don't know how to use POEdit anymore or has something changed?

### Panopticon version

1.2.1

### PHP version

8.2

### Database type

MySQL

### Database version

---

### Browser

None

**Comment by nikosdion** [comment]
The only new string was `PANOPTICON_SYSCONFIG_LBL_FIELD_BEHIND_LOAD_BALANCER_HELP` and it was found just fine. The only changed string was `PANOPTICON_SYSCONFIG_ERR_USING_ENVIRONMENT` and it was, too, found just fine.

**Comment by morphinestyle** [comment]
No, last string in italian is:
**msgctxt "PANOPTICON_ACTIONSUMMARYTASKS_LBL_PERIOD_MONTHLY"
msgid "Monthly"**

While in English I see many others, for example:

**msgctxt "PANOPTICON_SYSERROR_LEAKED_PASSWORD"
msgid "The password you are trying to use is present in online password leaks, making it very easy for hackers to guess this is what you are using. Please use a different password."**

OR

**msgctxt "PANOPTICON_SYSCONFIG_LBL_FIELD_AVATARS"
msgid "Show avatars for users"**

OR

**msgctxt "PANOPTICON_SYSERROR_FORBIDDEN_INFO"
msgid "Your IP address, <code>%s</code>, has been temporarily blocked due to suspicious behaviour."**

I can't find any of these strings that I can translate, and more.

**Comment by morphinestyle** [comment]
> The only new string was `PANOPTICON_SYSCONFIG_LBL_FIELD_BEHIND_LOAD_BALANCER_HELP` and it was found just fine. The only changed string was `PANOPTICON_SYSCONFIG_ERR_USING_ENVIRONMENT` and it was, too, found just fine.

I can't find these either.

**Comment by morphinestyle** [comment]
Solved, either I'm stoned, or something has changed in the latest versions of POEdit.
