### ISSUE TITLE
Template Override 

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#79]
As per the screenshot

![image](https://github.com/akeeba/panopticon/assets/1296369/52a04ea4-7bbe-4a94-a2be-ddb50f1363af)

**Comment by brianteeman** [comment]
corrected the screenshot

**Comment by nikosdion** [comment]
Try upgrading the connector.

I believe it's related to the fact that Joomla does not remove overrides to check when a template is removed.

If this is not the case, please check if the override to check refers to a file which no longer exists on the server and let me know.

**Comment by brianteeman** [comment]
nope - the error is still there. the template exists and the override file exists.

you can have access to the site if you want

**Comment by nikosdion** [comment]
Did you upgrade the connector?

**Comment by brianteeman** [comment]
yes

**Comment by brianteeman** [comment]
ooh - let me double check that I updated on all the sites

**Comment by nikosdion** [comment]
OK, this gives me a good place to start. Thank you!

**Comment by brianteeman** [comment]
yes definitely updated the connector on the site

**Comment by nikosdion** [comment]
> ooh - let me double check that I updated on all the sites

LOL! Okay, I'll wait :)
