### ISSUE TITLE
Uprade to 1.2.2 not working

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#790]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

In Panopticon press on Upgrade => nothing happens.

### Reproduction instructions

1. Go to …
2. Click on …
3. Scroll down to …

### Expected behaviour

Upgrade to 1.2.2

### Actual behaviour

Stays at 1.2.1

### Panopticon version

121

### PHP version

8.3

### Database type

MariaDB

### Database version

??

### Browser

Edge

**Comment by nikosdion** [comment]
Cannot reproduce. I upgraded both of my live installations to 1.2.2 yesterday using the process you described.

**Comment by brianteeman** [comment]
i just upgraded mine no problem

**Comment by NetSecond** [comment]
Ok, I found the problem: permissions while unpacking the downloaded update file.
I´ve chowned the whole Panopticon site again to www-data and it worked.
So far all updates have always worked, so I don't know why there were permission problems this time.
In this case, everything is fine and I have closed this (non)issue.
