### ISSUE TITLE
Feature: add checks for domain expiration

### ISSUE THREAD

**Issue by rvalitov** [akeeba/panopticon#808]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

It would be a good idea if Panopticon also had an interface with a list of expiration dates of all registered domain names. That's useful to monitor this info at one screen and also see this info inside website's view.

### Panopticon version

N/A

### PHP version

N/A

### Database type

MariaDB

### Database version

N/A

### Browser

None

**Comment by nikosdion** [comment]
This could be done. We would need an [external library to query the WHOIS database](https://github.com/io-developer/php-whois) and run this in the same manner we run the TLS certificate checks after retrieving a site's update information.

**Comment by brianteeman** [comment]
I would be in favour of this

**Comment by nikosdion** [comment]
Yup, that works beautifully.
![image](https://github.com/user-attachments/assets/2ed5295e-d474-412f-ae07-aee95e59a1ed)

I have to add the respective option and automatic task to notify you of domain expiration, but we're certainly getting there :)
