### ISSUE TITLE
Why #794 undone again?? (Update panopticon.pot / 3 small typos (missing "."))

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#809]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

In #794 I inserted 3 missing ".".

Now in new .POT they are removed again ?!?!

Why ??

### Panopticon version

1.2.3

### PHP version

8.1.3

### Database type

MySQL

### Database version

??

### Browser

None

**Comment by nikosdion** [comment]
Ah, I see the problem. In 794 you changed the POT, but not en-GB.ini.

The way the translations workflow works is en-GB.ini -> POT -> language PO -> language INI.

The whole reason for that is that INI files are easier to work with when developing features, but translation tooling for them is sorely missing. The best _translator_ experience is Poedit which only works with .po files. That's the only reason I convert the INI to POT and you work with .po files.

Don't worry, I'll fix the missing dots manually.

**Comment by nikosdion** [comment]
Closed with 79ef72679638fa9fe22e3e0fd7c7caa82e740319
