### ISSUE TITLE
Panopticon Connector: Pre Joomla 5 Update Warning message

### ISSUE THREAD

**Issue by david-unwin** [akeeba/panopticon#819]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

When doing the pre update check for Joomla 5 I get the message 
"Akeeba Panopticon Connector- System - Panopticon Troubleshooting Aid  Potential Upgrade Issue"
My question: Will this stop my migration from Joomla 4 to 5?

### Screenshots

![panopticon](https://github.com/user-attachments/assets/3a1c0867-e7f7-46d6-ad0b-66f7554ab1fd)

### Panopticon version

1.0.6

### PHP version

8.12

### Database type

MySQL

### Database version

8

### Browser

Chrome

### Additional information

This is on Joomla 4.4.8 system

**Comment by nikosdion** [comment]
Of course not. It's being _developed_ on Joomla! 5.2, it is of course compatible with Joomla! versions 4.0 to 5.2 inclusive.
