### ISSUE TITLE
BAD TRANSLATION. LANGUAGE KEY “PANOPTICON_TASK_JOOMLAUPDATE_LOG_BACKUP_DESCRIPTION” HAS THE WRONG NUMBER OR KIND OF VALUE ARGUMENTS.

### ISSUE THREAD

**Issue by pklinke** [akeeba/panopticon#824]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

On one site automatic panopticon backup shows this description in created akeeba backup pro:
BAD TRANSLATION. LANGUAGE KEY “PANOPTICON_TASK_JOOMLAUPDATE_LOG_BACKUP_DESCRIPTION” HAS THE WRONG NUMBER OR KIND OF VALUE ARGUMENTS.

Another site shows right text in German language.

### Screenshots

https://imgur.com/y3FOzI3

### Panopticon version

1.2.2.

### PHP version

8.3

### Database type

MySQL

### Database version

8.3

### Browser

None

### Additional information

The site with wrong description is J4.4.9, the site with right description is J5.1.4

**Comment by nikosdion** [comment]
Which language was used? Kindly note that I only have control over the English (UK) and Greek translations. For any other translation you have to tell me which language it is, so I can notify the respective language's author.

**Comment by NetSecond** [comment]
In german language I found a typo in this language key and corrected it.
So please try again after merged Pull Request.

Fast solution:
Open "de-DE.ini" on your site server and change following line:

Old:
`PANOPTICON_TASK_JOOMLAUPDATE_LOG_BACKUP_DESCRIPTION="Automatisches Backup erstellt durch Panopticon vor dem Upgrade auf Joomla! %S"`

New:
`PANOPTICON_TASK_JOOMLAUPDATE_LOG_BACKUP_DESCRIPTION="Automatisches Backup erstellt durch Panopticon vor dem Upgrade auf Joomla! %S"`

Please see the %S at the end and change it to %s ....

Sorry for the inconvenience and best regards
netsecond
