### ISSUE TITLE
unable to add site

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#835]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

i have a new build site Joomla 5.2 and unable to add it to panopticon. i tried everything i know and found trying to solve this issue.
with debug on i have a athentication error.

### Screenshots

![chrome_zmME7QHfHZ](https://github.com/user-attachments/assets/a3ee6f42-fca4-4397-aa4d-9c63f7d2c21f)

### Panopticon version

1.2.2

### PHP version

8.1

### Database type

MySQL

### Database version

8.0

### Browser

None

**Comment by nikosdion** [comment]
Joomla! cannot log you in with the API token you are using.

**Comment by johanpeters** [comment]
Hello Nikosdion,
still not working.. updated the panopticon. deleted tmp.. reinstall the panopticon client v1.0.6.
dubblecheck the code.. still same issue..

**Comment by nikosdion** [comment]
The only information you have given me says that the Joomla! API Token you are using is wrong. That's all the information I have, that's all I can tell you.
