### ISSUE TITLE
Link to changelog for extensions/plugins that have an update

### ISSUE THREAD

**Issue by Gileba** [akeeba/panopticon#837]
I like to read the changelog before updating an extension / plugin on a client site. Would it be possible to create a link (e.g. behind the new version number) from within Panopticon using the information from the manifest file? Same goes for new versions of Joomla / WP, though that's less important as I know where to find these much faster than every single extension.

**Comment by nikosdion** [comment]
This information is not collected, therefore it cannot be presented to you. You can always visit the site's backend and check the changelog at the appropriate location.
