### ISSUE TITLE
date timezone

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#84]
two issues - maybe related so reporting together

switched to a real server - tested with php 8.1 and 8.2 no difference

## Issue 1
Try to change the timezone in the sysconfig. It says saved but the value hasn't changed

## Issue 2
Try to add a new site
```
ErrorException:
Failed to parse time string (current_timestamp()) at position 0 (c): The timezone could not be found in the database (View template: /home/brian/scan.brianstest.site/tmp/compiled_templates/6d20d4eca5ef0f9f3fce7a576e4bb03e434f7390.php) (View template: /home/brian/scan.brianstest.site/tmp/compiled_templates/6d20d4eca5ef0f9f3fce7a576e4bb03e434f7390.php)

  at /home/brian/scan.brianstest.site/vendor/akeeba/awf/src/Date/Date.php:94
```

**Comment by brianteeman** [comment]
that fixed issue 1
issue 2 still remains

**Comment by nikosdion** [comment]
Pull the changes from the repo, run `composer install`, and `phing git`. It was a problem with the framework I fixed last week but forgot to update in the dependencies.

**Comment by brianteeman** [comment]
thanks
