### ISSUE TITLE
Double radio buttons for "Send email on success" in backup options

### ISSUE THREAD

**Issue by Martin511** [akeeba/panopticon#849]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

In the backup options area, there are 2 radio buttons with exactly the same name.

### Reproduction instructions

1. Go to backup options

### Expected behaviour

The names should be different.

### Actual behaviour

The names are the same.

### Screenshots

![Screenshot 2024-11-12 091519](https://github.com/user-attachments/assets/aa7c0ab7-85bc-4e11-8907-e1053cfb358e)

### Panopticon version

1.3.0

### PHP version

8.2

### Database type

MySQL

### Database version

unknown

### Browser

Firefox

**Comment by brianteeman** [comment]
This is what I see
![image](https://github.com/user-attachments/assets/8283dd38-9c8e-4b0d-b73d-955b70a10315)

**Comment by Martin511** [comment]
Hello Brian,
I have cleared the cache and deleted cookies and tested with a different browser - still showing the same label twice.
I have no explanation for this.

**Comment by Martin511** [comment]
👍
It was the tmp directory.
Deleting all files and folders there solved it.

**Comment by nikosdion** [comment]
The good news is that the update code in 1.3.0 will remove the contents of the `tmp` directory after upgrading to a newer version :)

**Comment by Martin511** [comment]
That makes sense.
Thank you.
