### ISSUE TITLE
Jobs do not work in containerised mode

### ISSUE THREAD

**Issue by alebak** [akeeba/panopticon#856]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Hello,

It seems that the jobs do not work through the panopticon CLI, the reason is that the cron system is very limited and does not take the previously configured environment variables.

### Reproduction instructions

Just run the docker image of panopticon 1.3.0 (the latest at the moment) and add the environment variables and you will get the cron running but the CLI not doing what it is supposed to do because of what is mentioned in the description.

### Expected behaviour

Run jobs in contenerised mode

### Actual behaviour

I added this job earlier to see what the cron returned:

`* * * * * * * env > /var/www/html/cron_env.log`

And I got the following:

```bash
panopticon@4681697c5f59:/var/www/html$ cat env_cron.log 
HOME=/home/panopticon
LOGNAME=panopticon
PATH=/usr/bin:/bin
SHELL=/bin/sh
PWD=/var/spool/cron
```

I modified the cron line by adding the following:

`* * * * * * /usr/local/bin/php /var/www/html/cli/panopticon.php task:run --loop >> /var/www/html/panopticon_cron.log 2>&1`

And I always got this output:

```bash
In AbstractCommand.php line 138:
                                                                        
  You need to configure Akeeba Panopticon before running this command.  
                                                                        

task:run [-l|--loop|--no--loop] [-d|--dummy [DUMMY]]
```

### Panopticon version

1.3.0

### PHP version

8.2.25

### Database type

MariaDB

### Database version

10.4.34

### Browser

None

### Additional information

I can think of a solution but I don't think you will like it and that is to leave the whole project in legacy mode, and that, the config.php file is generated according to the values of these environment variables. Too rustic that solution? Or do you have another idea to solve this problem with cron and jobs?

**Comment by nikosdion** [comment]
No need for such drastic measures. See https://stackoverflow.com/questions/27771781/how-can-i-access-docker-set-environment-variables-from-a-cron-job  I just implemented that suggestion and it works fine. I'll make a commit in a few minutes.
