### ISSUE TITLE
No option to switch from web cron to cli cron?

### ISSUE THREAD

**Issue by EricdeWaal** [akeeba/panopticon#859]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

I see no way, once a choice has been made for web cron, to switch to cli based cron.
Am I overlooking something or does it indeed not (yet) exist?

### Panopticon version

1.3.1

### PHP version

8.3.14

### Database type

MariaDB

### Database version

10.11.6-MariaDB-hetzner1 

### Browser

Firefox

### Browser version

134

**Comment by brianteeman** [comment]
I understand where @EricdeWaal is coming from. When I look at the page on my own site it looks like I might be using webcron (because I forgot that 6 months ago I created a real cron in my hosting control panel)

![image](https://github.com/user-attachments/assets/2da45b3f-9a71-4b9f-9e8d-3ddc58773d58)

**Comment by brianteeman** [comment]
and no I cant think of a way to make it clearer

**Comment by brianteeman** [comment]
Where is the CRON setup page?

**Comment by brianteeman** [comment]
ah - thats why i couldnt find it

**Comment by EricdeWaal** [comment]
Neither did I, hence my question!

⁣Met vriendelijke groet,

Eric de Waal


Op 4 dec 2024 19:22, om 19:22, Brian Teeman ***@***.***> schreef:
