### ISSUE TITLE
Updates only at certain times and days?

### ISSUE THREAD

**Issue by pklinke** [akeeba/panopticon#863]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

In my current solution (watchful), I can determine which days and times updates should be carried out. I can also set vacation times when there are no updates, but backups.

As I am not always available and in the office, I do not want my websites and those of customers to become unstable or crash due to an update and then have to deal with the solution while on vacation.

Is this possible or is this planned?

### Panopticon version

1.3.1

### PHP version

8.3.1ß

### Database type

MariaDB

### Database version

10.

### Browser

None

**Comment by nikosdion** [comment]
The most reasonable way to implement this use case is to not allow any automatic updates to take place without user interaction. 

Instead, every few days (when you are in your office) you can go into Panopticon's Overview, Core Updates and Overview, Extension Updates pages to select which updates you want to install on which sites.

Remember, this is not the same as going into each site in sequence to install updates. You can very easily select _all_ updates across multiple (or even all) sites, and have Panopticon queue them up for installation with one click, saving massive amounts of time.
