### ISSUE TITLE
admintools login failure

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#87]
Both sites I have added today (twice) are running admintools with it set to email on login failure

On adding each site it triggered the admintools loginfailure email to be sent.

**Comment by nikosdion** [comment]
When adding a site we check if the Joomla! API application is available and responds with the expected error message when we do not provide an authentication token. _This is deliberate_. This allows Panopticon to know if the Joomla! API application throws an error regardless of the existence of authentication information which would indicate something wrong with the server or site configuration.

Moreover, by not using an authentication token we make sure that any observed problem is _not_ the result of the server's mod_security2 or similar protection getting triggered by the long gibberish that's the authentication token.

Of course this counts as a login failure and it's reported as such.

**Comment by brianteeman** [comment]
makes sense.

probably should be documented somewhere. Sure I wont be the last person to comment

**Comment by brianteeman** [comment]
thanks
