### ISSUE TITLE
Log viewer page

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#9]
We should have a way to view the log files.

On this subject, we should contemplate exactly how to do that. Trying to dump an entire log file which might be several MiB big will freeze the browser. 

Can we come up with a way to display it a chunk at a time, like [Pimp My Log](https://github.com/potsky/PimpMyLog) used to do?

**Comment by brianteeman** [comment]
why not just fork pimpmylog and integrate it. the project is abandoned and it currently needs some trivial changes for php8 compatibility. there really is nothing else that comes close

**Comment by nikosdion** [comment]
Because I've looked at its code 😬 The code where it reads the log file is fairly simple and short. The part where it shows anything is insecure (since it was obviously made for local use, not a live server). 

It's far easier to replicate the small, easy part than try to shoehorn an insecure codebase into a framework and use case that's completely alien to it.

**Comment by brianteeman** [comment]
fair enough. plus I realised after I typed it that its designed for viewing the logs on the server it runs on whereas panopticon can be run on a different server to the one where it is monitoring sites

**Comment by nikosdion** [comment]
The logs are still on the same server as Panopticon. The whole point is, however, that we do not want to give the entire world access to these logs. We need to restrict access to authenticated users only. The logs can reveal too much about the remote sites they refer to. Hence the need to write custom code.

**Comment by brianteeman** [comment]
Sorry I realise now we were talking about different things/ You were correctly talking about the panopticon logs and I was mistakenly talking about the logs on the connected sites.
