### ISSUE TITLE
checkboxes a11y

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#96]
sorry I don't know how to do this in blade

everywhere you have code _similar_ to below you need to have a label for the checkbox

```
                <td>
                    @html('grid.id', ++$i, $user->id)
                </td>
```

something like

`<label for="cb0"><span class="visually-hidden">Select User</span></label>`

**Comment by nikosdion** [comment]
Needs to be fixed in AWF. Tracking in https://github.com/akeeba/awf/issues/11 and closed here

Note: this change will appear in Panopticon after releasing a new version of AWF and updating Panopticon's `composer.json` to use it.
